### ISSUE TITLE
libACPCampaign_iOS.a contains duplicate symbols

### ISSUE THREAD

**Issue by Mov1s** [Adobe-Marketing-Cloud/acp-sdks#105]
When linking with `libACPCampaign_iOS.a` the build fails with duplicate symbols. It appears that `Pods-ACPCampaign_iOS-dummy.o` has been included in the archive twice for each architecture.

**Comment by nporter-adbe** [comment]
Hi @Mov1s, would you mind sharing your `Podfile`?

**Comment by Mov1s** [comment]
I'm not using pods, I tried to link the lib manually as downloaded from the repo.

Build Error (XCode 10.1):
![Screen Shot 2019-03-22 at 4 28 34 PM](https://user-images.githubusercontent.com/1554256/54851298-cc34fd00-4cbf-11e9-9d20-8e39bb4a3ff8.png)

If you dump the symbols of the archive you can see that those symbols are indeed duplicated:
```
$ nm -j -arch arm64 libACPCampaign_iOS.a

. . .

libACPCampaign_iOS.a(Pods-ACPCampaign_iOS-dummy.o):
_OBJC_CLASS_$_NSObject
_OBJC_CLASS_$_PodsDummy_Pods_ACPCampaign_iOS
_OBJC_METACLASS_$_NSObject
_OBJC_METACLASS_$_PodsDummy_Pods_ACPCampaign_iOS
__objc_empty_cache

libACPCampaign_iOS.a(Pods-ACPCampaign_iOS-dummy.o):
_OBJC_CLASS_$_NSObject
_OBJC_CLASS_$_PodsDummy_Pods_ACPCampaign_iOS
_OBJC_METACLASS_$_NSObject
_OBJC_METACLASS_$_PodsDummy_Pods_ACPCampaign_iOS
__objc_empty_cache
$
```

I was able to fix it by removing one of objects from each arch and repackaging it:
```
$ lipo -thin armv7 libACPCampaign_iOS.a -output armv7.a
$ lipo -thin armv7s libACPCampaign_iOS.a -output armv7s.a
$ lipo -thin arm64 libACPCampaign_iOS.a -output arm64.a
$ lipo -thin i386 libACPCampaign_iOS.a -output i386.a
$ lipo -thin x86_64 libACPCampaign_iOS.a -output x86_64.a
$ ar -d armv7.a Pods-ACPCampaign_iOS-dummy.o
$ ar -d armv7s.a Pods-ACPCampaign_iOS-dummy.o
$ ar -d arm64.a Pods-ACPCampaign_iOS-dummy.o
$ ar -d i386.a Pods-ACPCampaign_iOS-dummy.o
$ ar -d x86_64.a Pods-ACPCampaign_iOS-dummy.o
$ lipo armv7.a armv7s.a arm64.a i386.a x86_64.a -create -output libACPCampaign_iOS_fixed.a
$
```

**Comment by nporter-adbe** [comment]
@Mov1s Thanks for the additional information. I've found the cause for the issue and we are working to get this fixed ASAP.

**Comment by rymorale** [comment]
The 1.0.1 campaign extension has been released which fixes this issue.
