### ISSUE TITLE
Unity support missing?

### ISSUE THREAD

**Issue by steve-ddigital** [Adobe-Marketing-Cloud/acp-sdks#130]
In the older mobile-services repo, there was Unity support ([at least up to September 2016](https://github.com/Adobe-Marketing-Cloud/mobile-services/issues/313) when it appeared to have stopped).  Since then the mobile-services SDK has been replaced by this SDK.  Is there a Unity plug-in that anyone has for this new SDK?

**Comment by imironchuk** [comment]
Hi Steve - The version of Unity you are referring to is still supported and should continue to work for sending app metrics to Adobe Analytics.

**Comment by steve-ddigital** [comment]
Thanks for the response.  I don't know if you read the issue in the other repo that I linked to, about the Unity SDK not working on iOS 11+.  Could you respond in that other issue?

**Comment by emdobrin** [comment]
Hi @steve-ddigital,

The unity package was updated, you can find the latest version here: https://github.com/Adobe-Marketing-Cloud/mobile-services/releases/tag/v4.18.8-Unity. 
Closing this issue now.

Emilia Dobrin
Computer Scientist
