### ISSUE TITLE
tvOS

### ISSUE THREAD

**Issue by AlexYehorov** [Adobe-Marketing-Cloud/acp-sdks#142]
Hello everyone! Could we integrate this sdks to tvOS??  I saw ACPCore contains WebKit, but tvOS does not support WebKit. 

Maybe you have a solution?

**Comment by nporter-adbe** [comment]
Hi @AlexYehorov 👋Currently the SDK does not support tvOS support but we're planning on adding support soon. The following link details which platforms we do/don't support:
https://aep-sdks.gitbook.io/docs/resources/upgrading-to-aep/aepvs4x#os-platform-support

cc: @imironchuk

**Comment by shalehaha** [comment]
@AlexYehorov 

We added the support for tvOS since the 2.7.0 release, https://aep-sdks.gitbook.io/docs/release-notes#june-17-2020. The tvOS libs do not rely on WebKit.

Jiabin
