### ISSUE TITLE
Illegal multi-threaded access to database connection

### ISSUE THREAD

**Issue by emadgniaYousee** [Adobe-Marketing-Cloud/acp-sdks#158]
## Hello everyone
In our iOS app, We used AdobeExperienceSDK, for more than two months we have this crash in most of our client's mobile, based on Apple Crash Report. 

`Test[46073:1964908] [logging] BUG IN CLIENT OF sqlite3.dylib: illegal multi-threaded access to database connection`

We don't use any kind of SQLite Database, And as I can see in xcconfig file based on pod file you use the SQLite database, Also I found some SQLite databases in catch directory.

``` OTHER_LDFLAGS = $(inherited) -ObjC -l"ACPAnalytics_iOS" -l"ACPCore_iOS" -l"ACPIdentity_iOS" -l"ACPLifecycle_iOS" -l"ACPSignal_iOS" -l"ACPUserProfile_iOS" -l"c++" -l"sqlite3.0" -l"z" -framework "ACPAnalytics" -framework "ACPCore" -framework "ACPUserProfile" ```

![Screenshot 2019-06-18 at 10 44 24](https://user-images.githubusercontent.com/51790366/59667080-6967da80-91b6-11e9-8ea3-5a4ada1ba427.png)

**Maybe you have a solution?**

**Comment by nporter-adbe** [comment]
Hi @emadgniaYousee 👋! What versions of libraries are you on?
I believe we fixed this issue in one of our latest releases, can you try updating to the latest versions and see if the crash persists?

https://aep-sdks.gitbook.io/docs/release-notes#may-9-2019

**Comment by emadgniaYousee** [comment]
Hi @nporter-adbe,  Thank you for your response, Yesterday I tried to update pod and it didn't work but today successfully updated and hopefully, That will be fixed.
