### ISSUE TITLE
Missing griffon-beta library for Android

### ISSUE THREAD

**Issue by cloudreyes** [Adobe-Marketing-Cloud/acp-sdks#167]
Error on Android after adding the Implementations as described on the Adobe Launch Install instructions for Android.

### ERROR: Failed to resolve: com.adobe.marketing.mobile:griffon-beta:0.+

When can we expect to have this on Maven?

**Comment by phuo1032** [comment]
Hi @cloudreyes, looks like you have the previous version of Griffon extension on Launch. Please update to the latest (0.2.0) to get the correct instruction for Android. We just recently released the Android Beta on Jun 28.

**Comment by cloudreyes** [comment]
Thanks, using 0.2.0 gave the same error. But using the libraries from the link worked. 

Thanks.

**Comment by phuo1032** [comment]
Hi @cloudreyes, I am glad to hear that the documentation link works for you. For investigating the installation instruction issue, can you please confirm that  **implementation 'com.adobe.marketing.mobile:griffonbridge:1.+'** is what you see? We'll look into it.

**Comment by cloudreyes** [comment]
I grabbed:
    implementation 'com.adobe.marketing.mobile:core:1.4.0' 
    implementation 'com.adobe.marketing.mobile:griffonbridge:1.0.1'
from the linked page.

On the original instructions, it was:
    implementation 'com.adobe.marketing.mobile:griffon-beta:0.+'

I grabbed that from the Mobile Install Instructions on the Environments tab on Adobe Launch.
