### ISSUE TITLE
Alternative APIs

### ISSUE THREAD

**Issue by ntanduc2288** [Adobe-Marketing-Cloud/acp-sdks#211]
Hi Adobe team,

I just upgrade to the latest SDK version and realized these APIs are deprecated.

1. Analytics.processReferrer()
2. Analytics.getTrackingIdentifier()
3. Visitor.getMarketingCloudId()

So what are alternative APIs for them?

Adobe versions:
    implementation 'com.adobe.marketing.mobile:target-vec:1.1.1'
    implementation 'com.adobe.marketing.mobile:target:1.1.2'
    implementation 'com.adobe.marketing.mobile:audience:1.0.1'
    implementation 'com.adobe.marketing.mobile:analytics:1.2.0'
    implementation 'com.adobe.marketing.mobile:userprofile:1.0.1'
    implementation 'com.adobe.marketing.mobile:sdk-core:1.4.4'

**Comment by phuo1032** [comment]
Hi @ntanduc2288, please refer to https://aep-sdks.gitbook.io/docs/resources/upgrading-to-aep/api-change-log for API changes in general.

For the ones you listed:
`Analytics.getTrackingIdentifier()` => https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-analytics/analytics-api-reference#gettrackingidentifier

`Visitor.getMarketingCloudId()` => https://aep-sdks.gitbook.io/docs/using-mobile-extensions/mobile-core/identity/identity-api-reference#get-experience-cloud-ids

`Analytics.processReferer` is undocumented, but it is moved under the MobileService extension, which supports acquisition capabilities from V4. Please refer to https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-analytics-mobile-services for more detail regarding to this extension. The API will be `MobileServices.processReferrer(final Context context, final Intent intent)`

**Comment by ntanduc2288** [comment]
Thanks for the prompt update.

1. For the Analytics.getTrackingIdentifier(), it always returns null in the callback. I'd tried to get visitor but it returns null also.

2. For Analytics.processReferer: How to add MobileServices extension to project?

Could you walk me through the above things?
Thanks in advance.

**Comment by shalehaha** [comment]
@ntanduc2288 
1. `Analytics.getTrackingIdentifier()` returns AID(https://docs.adobe.com/content/help/en/analytics/implementation/javascript-implementation/unique-visitors/visid-analytics.html). For a new user, SDK only generates the AID  when the grace peirod is enabled (https://docs.adobe.com/content/help/en/id-service/using/reference/analytics-reference/grace-period.html).

2. Please follow the docs here, https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-analytics-mobile-services

Let us know if you have further questions.

**Comment by ntanduc2288** [comment]
@shalehaha 

For #1: Looks like that docs are used for Web, how about Mobile. I'm new in Adobe (baby step would be more helpful. Thanks).

#2: Tried to follow instructions but MobileServices class is not found. I though it's under Core extension but couldn't find it. Do I need to add some more library along with these:
implementation 'com.adobe.marketing.mobile:target-vec:1.+'
    implementation 'com.adobe.marketing.mobile:target:1.+'
    implementation 'com.adobe.marketing.mobile:audience:1.+'
    implementation 'com.adobe.marketing.mobile:analytics:1.+'
    implementation 'com.adobe.marketing.mobile:userprofile:1.+'
    implementation 'com.adobe.marketing.mobile:sdk-core:1.+'

**Comment by shalehaha** [comment]
@ntanduc2288 
1. The same rules apply for Mobile. What is the use case here to get the `TrackingIdentifier`?
2. In the Launch UI, there is an extension named `Adobe Analytics – Mobile Services`, you have to enable it and also link it to a correct Mobile Services App. After that, you can go to check the install instruction, it should get updated with the Mobile services lib.  Or if you want, you can manually include it `com.adobe.marketing.mobile:mobileservices:1.+`

**Comment by ntanduc2288** [comment]
@shalehaha 

#1: I need it to create an adobeCookie as our project requires.
return Observable.create(subscriber -> {
            Analytics.getTrackingIdentifier(new AdobeCallback<String>() {
                @Override
                public void call(String s) {
                    subscriber.onNext(s);  **// s is null here**
                }
            });
        });

#2: It works. Thanks

**Comment by shalehaha** [comment]
@ntanduc2288 
Then you need to handle the scenario where the `getTrackingIdentifier` may return null.

**Comment by ntanduc2288** [comment]
Thanks for your supports!
