### ISSUE TITLE
React Native issue when sending IOS token to ACS

### ISSUE THREAD

**Issue by Robsay** [Adobe-Marketing-Cloud/acp-sdks#212]
We are currently working on making IOS subscriptions work through React Native but the push tokens end up converted/encoded/changed when they reach Adobe.  The PEM is uploaded successfully. When using ACPCore.setPushIdentifier("pushIdentifier");  the tokens ends up as a pure alphanumeric string with only [0-9][A-Z][a-z] and no special characters!? for instance: 657173315F6156675164413A4150413931624573754D744A6A5747735A36304A3151726A317969525F715954486D48554867416E497933354937705A2D4F7037775F387A72347047315446306541375A557A5252536B553475585F443567594D6A79323656463053744247755443494A667134773959642D6D6479354551492D

**Comment by nporter-adbe** [comment]
Which version of react-native-acpcore are you using? This should be fixed by upgrading to the latest version.

________________________________
