### ISSUE TITLE
./ACPCore/libACPCore_iOS.a is using UIWebview, Because of this Appstore might reject the apps having deprecated API's

### ISSUE THREAD

**Issue by narasimharaok** [Adobe-Marketing-Cloud/acp-sdks#221]
I have scanned the ACPCore binaries using grep -r "UIWebView" .
Found "Binary file ./ACPCore/libACPCore_iOS.a matches"

When we upload the binary to appstore we get the below warning.

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by shalehaha** [comment]
@narasimharaok 
We will release a build next week to address this issue.

**Comment by narasimharaok** [comment]
Thanks for the quick response.

**Comment by shalehaha** [comment]
@narasimharaok 

Fixed in the 2.3.4 release, check out the release notes https://aep-sdks.gitbook.io/docs/release-notes#october-4-2019.
