### ISSUE TITLE
ACPIdentity methods not returning callbacks upon unsuccessful config registration

### ISSUE THREAD

**Issue by alex-sazhnov** [Adobe-Marketing-Cloud/acp-sdks#259]
Upon providing non-existent or invalid Launch property id, an app would reject all ACPIdentity calls and no callbacks will be received.

> [AdobeExperienceSDK TRACE <com.adobe.module.identity>]: Config settings not valid to process the identity event. Processing will resume when a valid configuration is obtained.

SDK provides no way to determine whether it was configured successfully or not.

```
ACPCore.configure(withAppId: "incorrect-id")
ACPIdentity.registerExtension()
        
ACPCore.start {
     ACPCore.lifecycleStart(nil)
}
        
ACPIdentity.getUrlVariables { (result) in
     print ("We will never land here if the AppId is incorrect")
}
```

**Comment by alex-sazhnov** [comment]
**Correction:** 
All extensions will have similar behavior. I assume due to the fact they were not successfully
registered with ACPCore.

**Comment by kevinlind** [comment]
Hi @alex-sazhnov,

Without a valid Adobe Experience Cloud Organization ID, which is typically obtained from the Launch configuration, the SDK will not function correctly. In your application logs, you should see a series of warnings and errors such as the following:

> [AdobeExperienceSDK WARNING <ConfigurationDownloader>]: Failed to find cacheed config at https://assets.adobedtm.com/incorrect-id.json
> [AdobeExperienceSDK WARNING <ConfigurationDownloader>]: Failed to download config from https://assets.adobedtm.com/incorrect-id.json
> [AdobeExperienceSDK ERROR <com.adobe.module.configuration>]: Unable to fetch config. Rolling back to previous configuration.

If you do not see the above logs, please let me know. To correctly setup your SDK extensions with your Experience Cloud Organization ID, you can follow the instructions here, https://aep-sdks.gitbook.io/docs/getting-started/create-a-mobile-property#set-up-your-extensions

Thanks,
**Kevin Lind**
*Mobile Software Engineer*
[Adobe Experience Cloud](https://www.adobe.com/experience-cloud.html)

**Comment by alex-sazhnov** [comment]
Hi @kevinlind ,

Appreciate your reply!

It kind of makes sense, but there is still no way programmatically detect if the initialization with a certain config failed. In the app logs you would see the warnings you mentioned above, but that's it.
My point is, there is nothing failable in the initialization process and all I can't seem to find any way to detect that by calling any of the SDK methods.

Thanks,

**Comment by kevinlind** [comment]
Hi @alex-sazhnov ,

Can you give a little more information about your use-case. It would be helpful to understand how your application would respond if an API or callback method was available to report such errors?

If you haven't already done so, I would suggest bundling an `ADBMobileConfig.json` with your application to act as a fallback configuration. When your application is loaded, the bundled configuration is used if no cached configuration is found. You application will use this bundled configuration if the call to `ACPCore.configure(withAppId:)` fails in the the case of incorrectly set Launch ID or if there is no network connectivity. The instructions for including a bundled configuration are here, https://aep-sdks.gitbook.io/docs/using-mobile-extensions/mobile-core/configuration/configuration-api-reference#using-a-bundled-file-configuration

Also, to clarify a point, the extensions are being registered correctly with the SDK, it's the call to `ACPCore.configure(withAppId: "incorrect-id")` which is failing. However, most of the extensions will not work properly without a valid configuration. They are essentially waiting for a valid configuration to be set.

Thanks,
**Kevin Lind**
_Mobile Software Engineer_
[Adobe Experience Cloud](https://www.adobe.com/experience-cloud.html)

**Comment by alex-sazhnov** [comment]
Hi @kevinlind,

We do have everything in place. Maybe I was not clear enough with my question. Is there any way to detect that the SDK is failing to register. So far the only way to tell for me is by calling:
```
ACPCore.getSdkIdentities { sdkIdentities in
       // check if sdkIdentities string is longer than the following: {'\n\n'}
       // {'\n\n'} is being returned when the SDK failed to initialize

      // here now we can log SDK init error with NewRelic for example
}
```

Is there a better way of detecting that?


Thanks,

**Comment by kevinlind** [comment]
Hi @alex-sazhnov ,

Thanks for the details. Unfortunately there is currently no good way to achieve what you are attempting. The Mobile SDK doesn't have a mechanism to report these types of errors back to the application. I have added a few internal tickets to my team to look into these issues, specifically to add a way to report these failures and to guarantee that callbacks get called.

As it stands, I think your current approach of calling `ACPCore.getSdkIdentities` is good, however if you are specifically interested whether ACPIdentity is configured, I would suggest checking for the existence of the Experience Cloud Org ID in the result. If you integrate with other Experience Cloud solutions, such as Target, Analytics, or Audience Manager, identifiers may still be set in the SDK.  In the `getSdkIdentifiers` result, if the Experience Cloud Org ID exists, it is listed under the namespace "imsOrgID" in the "companyContexts" array.
```
  "companyContexts" : [
    {
      "namespace" : "imsOrgID",
      "value" : "<yourOrgId>@AdobeOrg"
    }
  ]
```

Thanks,
**Kevin Lind**
_Mobile Software Engineer_
[Adobe Experience Cloud](https://www.adobe.com/experience-cloud.html)

**Comment by shalehaha** [comment]
@alex-sazhnov 

A new method `getUrlVariablesWithCompletionHandler` was added in ACPCore version 2.5.0(ACPIdentity version 2.2.0). Please reference https://aep-sdks.gitbook.io/docs/using-mobile-extensions/mobile-core/identity/identity-api-reference#geturlvariables-2.
