### ISSUE TITLE
Question about trackTimedAction from 4.*

### ISSUE THREAD

**Issue by Vacxe** [Adobe-Marketing-Cloud/acp-sdks#274]
I have look at new library API and can't find any method what can be equivalent for `trackTimedActionStart` and `trackTimedActionEnd` in 4.* version

Does it mean that this feature isn't supported or you have alternatives?

**Comment by praschetan** [comment]
@Vacxe - those APIs were deprecated in the new SDKs due to lack of adoption in the 4x SDK and low user relevance in the Adobe Analytics UI. Please see - https://aep-sdks.gitbook.io/docs/resources/upgrading-to-aep/aepvs4x#adobe-analytics.
