### ISSUE TITLE
Parallel support for ACP SDK and the old AdobeMobileLibrary

### ISSUE THREAD

**Issue by cweatureapps** [Adobe-Marketing-Cloud/acp-sdks#277]
Hi,

We have a very large app with many years of code and countless features. 
With the end of life of the older AdobeMobileLibrary, we would like to upgrade to the new ACP SDK.

However, it is not feasible to do this in a "Big Bang" migration. We would like to adopt a phased approach, linking against both libraries, and dynamically changing which library is used based on flags/switches etc. , fully migrating over when testing is complete.

**_Do you support including both ACP SDK and the old AdobeMobileLibrary in the same app?_**

It seems there are some internal/private classes exposed to Objective-C which cause a duplicate symbol error when both libraries are included.

This this compile error, where `ADBAlertViewController` is duplicated in both `ACPCore` and `AdobeMobileLibrary`:

`duplicate symbol '_OBJC_CLASS_$_ADBAlertViewController' in:
    /Users/kenko/dev/myapp.ios/Vendor/Checkouts/AdobeMobileLibrary/AdobeMobileLibrary/AdobeMobileLibrary.a(ADBMessageAlert.o)
    /Users/kenko/dev/myapp.ios/Vendor/Checkouts/AdobeCloudPlatformSDK/ACPCore/ACPCore_iOS.a(ADBAlertHandler.o)
duplicate symbol '_OBJC_METACLASS_$_ADBAlertViewController' in:
    /Users/kenko/dev/myapp.ios/Vendor/Checkouts/AdobeMobileLibrary/AdobeMobileLibrary/AdobeMobileLibrary.a(ADBMessageAlert.o)
    /Users/kenko/dev/myapp.ios/Vendor/Checkouts/AdobeCloudPlatformSDK/ACPCore/ACPCore_iOS.a(ADBAlertHandler.o)
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by cweatureapps** [comment]
As another example, using the default cococapods integration:

```
  # Adobe ACP Pods
  pod 'ACPCore', '~> 2.0'
  pod 'ACPAnalytics', '~> 2.0'

  # Legacy AdobeMobileLibrary
  pod 'AdobeMobileSDK'

```


You get a runtime warning:

```
objc[66820]: Class ADBAlertViewController is implemented in both /Users/kenko/Library/Developer/CoreSimulator/Devices/05610612-6CA8-4077-BA4E-591FA3252306/data/Containers/Bundle/Application/3D895CDB-E4DE-419C-9066-3BB8C0B2EAD2/Sample.app/Frameworks/AdobeMobileSDK.framework/AdobeMobileSDK (0x105b99b98) 
and /Users/kenko/Library/Developer/CoreSimulator/Devices/05610612-6CA8-4077-BA4E-591FA3252306/data/Containers/Bundle/Application/3D895CDB-E4DE-419C-9066-3BB8C0B2EAD2/Sample.app/Sample (0x1055dceb8). 
One of the two will be used. Which one is undefined.
```

**Comment by ahmyr** [comment]
We do not support including both AEP SDK and the old AdobeMobileLibrary in the same app. I would suggest looking through the upgrade documentation for details on how to manage the upgrade process: https://aep-sdks.gitbook.io/docs/resources/upgrading-to-aep

You might also look at the Adobe Analytics - Mobile Services extension in AEP SDK. This will allow you to use in-app messaging, push notifications, and marketing links functionality from Mobile Services with the AEP SDK.
https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-analytics-mobile-services

Amber Hardy
Adobe Mobile Engineering
