### ISSUE TITLE
Handling InApp messages

### ISSUE THREAD

**Issue by alex-sazhnov** [Adobe-Marketing-Cloud/acp-sdks#290]
Would it be possible to expose a method to control the process of presenting an inApp message that is sent from Adobe Campaign Standard?
Currently, there is no visibility over that process:

Why we believe this feature is needed:
- there is no way to control the size of the webView, meaning it takes over the entire screen. In our use cases, we would like to have a low aggression message(like a banner almost) that would still allow users to interact with the app without having to click through the message or dismiss it.
- webView transition cannot be changed (how it's shown and dismissed).
- unable to add custom logic around showing inApp messages (firing additional beacons etc.)

Having a delegate method somewhat like following would help a lot:
`func aboutToPresentMessage(with html: String, broadlogId: String, deliveryId: String ) { }`

Let us know if that is possible/ can be added to the product's roadmap.

Thank you,
Alex

**Comment by praschetan** [comment]
@alex-sazhnov - we don't have plans to support this functionality in the SDK at this time. Recommend contacting your Adobe CSM for more information on how this may be prioritized.
