### ISSUE TITLE
EXC_BAD_ACCESS when passing nil callback to ACPCampaignClassic.registerDevice

### ISSUE THREAD

**Issue by julienbodet** [Adobe-Marketing-Cloud/acp-sdks#332]
From Swift, I call `ACPCampaignClassic.registerDevice` by passing a nil callback.
I get the following crash:

```
Thread 23: EXC_BAD_ACCESS (code=1, address=0x10)
```

I'm using ACPCampaignClassic version 2.0.2.

**Comment by rymorale** [comment]
Thanks for the heads up @julienbodet. We will get this fixed for the next release.

Ryan Morales
Mobile Engineer
[Adobe Experience Cloud](https://www.adobe.com/experience-cloud.html)

**Comment by rymorale** [comment]
This issue is resolved in the latest ACPCampaignClassic release (version 2.0.3). Closing this issue.

Ryan Morales
Mobile Engineer
[Adobe Experience Cloud](https://www.adobe.com/experience-cloud.html)
