### ISSUE TITLE
iOS SDK Crash EXC_BAD_ACCESS (code=1, address=0x0)

### ISSUE THREAD

**Issue by jarad-kears** [Adobe-Marketing-Cloud/acp-sdks#336]
When trying to call configure in a framework the app crashes. Below is how the app's delegate initializes the framework. In MyClass.swift the framework attempts to start the ACP service but crashes.

AppDelegate.swift

```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {

        // Override point for customization after application launch.
        let x = MyClass()
        x.start(application: application, launchOptions: launchOptions, production: false, deviceId: "test")
        return true
    }
```

MyClass.swift

```
public func start(application: UIApplication, launchOptions: [UIApplication.LaunchOptionsKey : Any]?, production: Bool, deviceId: String) {

        ACPCore.setLogLevel(.debug)
        ACPCore.configure(withAppId: "appId")
        ACPCore.start {
            ACPCore.lifecycleStart(nil)

        }
    }
```

**Comment by sbenedicadb** [comment]
Hey @jarad-kears,

Can you provide more information from your crash?  A log or stack trace would be helpful.

I tried to reproduce the issue with the provided code above, but I don't get a crash.  What version of the cocoapods are you using?

**steve benedick**
*sr mobile software engineer*
[Adobe Experience Cloud](http://www.adobe.com/experience-cloud.html)

**Comment by jarad-kears** [comment]
I have attached a sample project here 

https://www.dropbox.com/s/91a86nurimdjbi0/AdobeTest.zip?dl=0

The log doesn't print anything even when I set logging to verbose 
This is all I get

>  EXC_BAD_ACCESS (code=1, address=0x0)

Even with zombies enabled I don't even get info about what is trying to be acessed.

When you used the code above was MyClass.swift in a separate or a class in the main project framework?

**Comment by jarad-kears** [comment]
Also cocoapods 1.8.4 and SDK version 2.5

**Comment by shalehaha** [comment]
@jarad-kears 

We can reproduce the crash and saw the logs like:
```
AdobeTest[42160:8572164] dynamic_cast error 2: One or more of the following type_info's has hidden visibility or is defined in more than one translation unit. They should all have public visibility. N20AdobeMarketingMobile23ModuleEventListenerBaseE, N20AdobeMarketingMobile45ConfigurationListenerLifecycleResponseContentE, N20AdobeMarketingMobile15OneTimeListenerE.
2020-03-02 09:18:03.736548-0700 AdobeTest[42160:8571660] [AdobeExperienceSDK DEBUG <Core>]: Registered Configuration module
2020-03-02 09:18:03.742912-0700 AdobeTest[42160:8572164] dynamic_cast error 2: One or more of the following type_info's has hidden visibility or is defined in more than one translation unit. They should all have public visibility. N20AdobeMarketingMobile23ModuleEventListenerBaseE, N20AdobeMarketingMobile35ConfigurationListenerHubSharedStateE, N20AdobeMarketingMobile15OneTimeListenerE.
```

This is because, in the Pod file, the SDK has been included twice:
```
abstract_target 'TestAbstractTarget' do
  pod 'ACPCore'
  pod 'ACPAnalytics'


  target 'AdobeTest' do
    inherit! :complete
  end
  
end


def shared_pods
  pod 'ACPCore'
  pod 'ACPAnalytics'
end
```

If you want to use a shared framework to embed SDK, then in your main app, you should only use it and do not directly include SDK again. 

I hope this helps and let us know if you have any other questions.

Jiabin

**Comment by jarad-kears** [comment]
Following your suggestions and coworkers, limiting the view of the pod does in fact fix the problem. FYI, if you have multiple pod targets you can't have it in shared pods either. It must be in the specific target you plan on using.
