### ISSUE TITLE
Upgrade to the Experience Platform SDKs Issue.

### ISSUE THREAD

**Issue by gundam** [Adobe-Marketing-Cloud/acp-sdks#343]
Hello.
When I  upgrade to the Experience Platform SDKs from 4x SDKs.
Some change APIs I did not get. Can you help to check? I use the Experience Platform SDKs  ACPCore(2.5.0).
1.
 ![image](https://user-images.githubusercontent.com/1777944/76162666-ceb38f80-617a-11ea-9aa2-d8eecf2e1309.png)
`getMarketingCloudID` method I can't find.
2. 4x API  `[ADBMobile trackPushMessageClickThrough:userInfo]` I can't find how to change it.

Thank you very much.

**Comment by emdobrin** [comment]
Hi @gundam ,

1. The Marketing Cloud ID (MID) is now called Experience Cloud ID (ECID) and the new API for fetching this value is [getExperienceCloudId](https://aep-sdks.gitbook.io/docs/using-mobile-extensions/mobile-core/identity/identity-api-reference#getexperiencecloudid) available in the ACPIdentity (iOS) / Identity (Android) extension.
2. You can implement push tracking in multiple ways with the Adobe Experience Platform Mobile SDKs, depending on which extension you are using:
   - For the Campaign Standard extension, see [Push Tracking](https://helpx.adobe.com/campaign/kb/push-tracking.html).
   - If you use the Campaign classic extension, see [Tracking push notifications](https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-campaignclassic/adobe-campaignclassic-api-reference#tracknotification-api).
   - For Adobe Analytics - Mobile Services extension, see [Set up push tracking](https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-analytics-mobile-services#set-up-push-tracking).

Thanks,
**Emilia Dobrin**
Computer Scientist
[Adobe Experience Cloud](http://www.adobe.com/experience-cloud.html)

**Comment by gundam** [comment]
Great job!!
Thank you very much!!!
