### ISSUE TITLE
outdated README.md

### ISSUE THREAD

**Issue by evaristokbza** [Adobe-Marketing-Cloud/acp-sdks#379]
Latest versions section in README.md is not updated. 

Specifically, **iOS** link for **Adobe Analytics - Mobile Services** points to 1.0.0 release and not to the latest one.

**Comment by sbenedicadb** [comment]
Hey @evaristokbza,

Thanks for letting us know.  I've updated the link for Mobile Services to point to the correct page.

-steveb
