### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by Meous** [Adobe-Marketing-Cloud/acp-sdks#388]
Sorry but I cannot see the react native SDK implementation methods

**Comment by sbenedicadb** [comment]
Hey @Meous, 

I think the `Usage` section of the React Native repo is what you're looking for.  Let me know if this helps.

https://github.com/adobe/react-native-acpcore#usage

Thanks.

-steveb

**Comment by Meous** [comment]
Hey,

Got it,

Many thanks.

Kwame.
