### ISSUE TITLE
Android - 404 on https://assets.adobedtm.com/

### ISSUE THREAD

**Issue by nishantkp** [Adobe-Marketing-Cloud/acp-sdks#395]
Hello,

I am not able to send any tracking events, when I see in Charles logs there is 404 on https://assets.adobedtm.com/*****(app-id).json. 
Also i am not seeing any error logs regarding this in android studio.

ADMMobileConfig.json is in assets folder.
Media core version used is 1.5.4.

I am not sure whats causing it.

**Comment by shalehaha** [comment]
@nishantkp 

Have you published the Launch property? You can follow the steps from https://aep-sdks.gitbook.io/docs/getting-started/create-a-mobile-property#publish-the-configuration, this should fix the 404 issue when assuming the app id is correct.

If you have configured the app-id in code, there is no need to include ADBMobileConfig.json in the assets folder. 

Let us know if you have further questions.

- Jiabin

**Comment by praschetan** [comment]
@nishantkp - generally speaking - quickly skimming over the "Getting Started" section (on SDK documentation - https://sdkdocs.com) should give you an orientation on how to move forward.
