### ISSUE TITLE
How to disable ssl on Analytics?

### ISSUE THREAD

**Issue by nishantkp** [Adobe-Marketing-Cloud/acp-sdks#402]
We have ssl settings to false on ADBMobileConfig, but when i switched to Launch Platform, extension doesn't give flexibility for setting ssl to false.

I have tried with,
```java
HashMap<String, Object> data = new HashMap<>();
data.put("analytics.ssl", false);
MobileCore.start(o -> MobileCore.configureWithAppID("id"));
MobileCore.updateConfiguration(data);  
```

but it didn't help.

Can you help me with this?

**Comment by emdobrin** [comment]
Hi @nishantkp ,

This configuration setting is not available anymore with AEP SDKs, the network connections are SSL enabled by default.

Emilia Dobrin
Computer Scientist 
[Adobe Experience Cloud](http://www.adobe.com/experience-cloud.html)

**Comment by nishantkp** [comment]
@emdobrin 

gotcha, thanks a bunch
