### ISSUE TITLE
ACPCore pod dependency (private podspec) shows undefined symbol error

### ISSUE THREAD

**Issue by iosmagesh18** [Adobe-Marketing-Cloud/acp-sdks#423]
I've been struggling with the "Undefined symbol: _OBJC_CLASS_$_ACPCore" problem when an application that uses ACPCore (as a pod) where it is added as a dependency in one of our private podspec.

The app consists of a main application project, and some private podspec as a pod dependency, each with their own dependencies. So, ACPCore is one of the dependencies in our private podspec.

**Note:** I have a private podspec that has a ACPCore as a pod dependency.

The problem is that we are not able to access the ACPCore in the main application. So, I’m having trouble getting my workspace to compile correctly with private podspec that contains ACPCore.

I am using Xcode 11.3.1, Swift 4.2

Am I missing something? How can this be fixed? Any help would be really appreciated.

<img width="307" alt="Screenshot 2020-08-29 at 12 31 19 PM" src="https://user-images.githubusercontent.com/70427610/91631379-c6843080-e9f6-11ea-9aa3-b0b39c475daf.png">
<img width="379" alt="Screenshot 2020-08-29 at 12 33 52 PM" src="https://user-images.githubusercontent.com/70427610/91631385-c97f2100-e9f6-11ea-9067-8789574b5e70.png">

**Comment by shalehaha** [comment]
@iosmagesh18 

Can you check whether ACPCore has been installed under the `Pods` folder of the main app?
In your private podspec, have you declared ACPCore as a dependency? 

Jiabin

**Comment by iosmagesh18** [comment]
Thanks for the reply @shalehaha 

Yes,  ACPCore and its related files have been installed under the Pods directory of the main app.

Also, we have added ACPCore as a dependency in our private podspec. 

Below is our project hierarchy,

Main application        
          |_____Private podspec - this is referring to the dynamic library and it contains ACPCore as a pod dependency.                                                  |______ACPCore - which contains static libraries

So, The problem is how do we mix and match the static and dynamic libraries with pods?. 
Please let us know if you need more details on this.  

Thanks!

**Comment by shalehaha** [comment]
@iosmagesh18 

Are you able to provide a sample project to reproduce this problem?

**Comment by iosmagesh18** [comment]
@shalehaha  

Please find the sample source code [here](https://github.com/iosmagesh18/MyRepo.git),

We have created a sample project (SampleACPCore) and added two podspecs named MyOtherPod and MyPrivateObjcPod.

MyOtherPod holds the MyPrivateObjcPod which contains “ACPCore” as a pod dependency, which in turn contains static libraries.

So, you will be getting this issue “Undefined symbol: _OBJC_CLASS_$_ACPCore” once you have done the pod installation and start compiling it.

Thanks!
Magesh M

**Comment by shalehaha** [comment]
@iosmagesh18 

The error happened actually when compiling `MyOtherPod`.  If I added `s.static_framework = true` to `MyOtherPod.podspec`, then it was able to successfully compile the app.

So basically, for any pod that depends on ACPCore, no matter direct or transitive, the pod has to be declared as a static framework. It is quite tricky when deal with those compile options, I'm not sure if there is any other more elegant way to handle this.

Hope this helps, let me know if you have any other questions.

Jiabin

**Comment by iosmagesh18** [comment]
@shalehaha 

Thanks for taking your time looking into this issue. Highly appreciate it!

Unfortunately, adding "s.static_framework = true" is not a solution that works for us, we have nearly 20+ pods integrated & don't really want to mess up the existing configuration of our project/ecosystem.

We thought that there would exist some solution for this issue and hence wanted to ask for help, but it looks like there is none after digging deep.

The only elegant solution would be to get these pods built as dynamic frameworks instead of static libraries. 
Is there any timeline from the Adobe team for when this could happen?

Thanks!
Magesh M

**Comment by shalehaha** [comment]
@iosmagesh18 

We are working on a new version of SDK written in Swift, which will be open-sourced. I believe that will give more flexibility regarding how it can be used in the different project structures. 

You can sign up at https://aep-sdks.gitbook.io/docs/#swift-developer-preview

Jiabin

**Comment by iosmagesh18** [comment]
@shalehaha.  

That's good to hear!!! 

Thanks for the update and we are expecting the Swift SDK version at the earliest. 

Thanks!
Magesh M
