### ISSUE TITLE
Missing griffon-beta library for iOS

### ISSUE THREAD

**Issue by vzfintechgit** [Adobe-Marketing-Cloud/acp-sdks#443]
Hello.

It seem flutter griffon for iOS is calling the V1.0.0 that expose endSession, attemptReconnect, sendEvent methods, after seeing the history changelog I figured out this methods was remove from current version 1.2.0.

![Screen Shot 2020-09-24 at 4 55 08 PM](https://user-images.githubusercontent.com/68557405/94460336-31539380-017e-11eb-923c-83200f9bf4ec.png)

Flutter dependency `flutter_griffon: ^1.0.0-beta.3` 

Podfile.lock

PODS:
  - ACPAnalytics (2.3.0):
    - ACPAnalytics/main (= 2.3.0)
    - ACPCore (>= 2.5.0)
  - ACPAnalytics/main (2.3.0):
    - ACPCore (>= 2.5.0)
  - ACPCore (2.7.5):
    - ACPCore/main (= 2.7.5)
  - ACPCore/main (2.7.5)
  - ACPGriffon (1.2.0):
    - ACPCore
    - ACPGriffon/iOS (= 1.2.0)
  - ACPGriffon/iOS (1.2.0):
    - ACPCore
  - ACPUserProfile (2.1.0):
    - ACPCore (~> 2.0)
    - ACPUserProfile/iOS (= 2.1.0)
  - ACPUserProfile/iOS (2.1.0):
    - ACPCore (~> 2.0)
  - AppCenter (3.3.4):
    - AppCenter/Analytics (= 3.3.4)
    - AppCenter/Crashes (= 3.3.4)
  - AppCenter/Analytics (3.3.4):
    - AppCenter/Core
  - AppCenter/Core (3.3.4)
  - AppCenter/Crashes (3.3.4):
    - AppCenter/Core
  - Flutter (1.0.0)
  - flutter_acpanalytics (0.0.1):
    - ACPAnalytics (~> 2.2)
    - Flutter
  - flutter_acpcore (0.0.1):
    - ACPCore (~> 2.5)
    - Flutter
  - flutter_acpuserprofile (1.0.0):
    - ACPUserProfile
    - Flutter
  - flutter_griffon (0.0.1):
    - ACPGriffon
    - Flutter
  - FMDB (2.7.5):
    - FMDB/standard (= 2.7.5)
  - FMDB/standard (2.7.5)
  - Instabug (9.1.6)
  - instabug_flutter (0.0.1):
    - Flutter
    - Instabug (= 9.1.6)
  - package_info (0.0.1):
    - Flutter
  - path_provider (0.0.1):
    - Flutter
  - path_provider_linux (0.0.1):
    - Flutter
  - path_provider_macos (0.0.1):
    - Flutter
  - path_provider_windows (0.0.1):
    - Flutter
  - sqflite (0.0.1):
    - Flutter
    - FMDB (~> 2.7.2)
  - url_launcher (0.0.1):
    - Flutter

DEPENDENCIES:
  - AppCenter
  - Flutter (from `Flutter`)
  - flutter_acpanalytics (from `.symlinks/plugins/flutter_acpanalytics/ios`)
  - flutter_acpcore (from `.symlinks/plugins/flutter_acpcore/ios`)
  - flutter_acpuserprofile (from `.symlinks/plugins/flutter_acpuserprofile/ios`)
  - flutter_griffon (from `.symlinks/plugins/flutter_griffon/ios`)
  - Instabug (from `./Instabug.podspec`)
  - instabug_flutter (from `.symlinks/plugins/instabug_flutter/ios`)
  - package_info (from `.symlinks/plugins/package_info/ios`)
  - path_provider (from `.symlinks/plugins/path_provider/ios`)
  - path_provider_linux (from `.symlinks/plugins/path_provider_linux/ios`)
  - path_provider_macos (from `.symlinks/plugins/path_provider_macos/ios`)
  - path_provider_windows (from `.symlinks/plugins/path_provider_windows/ios`)
  - sqflite (from `.symlinks/plugins/sqflite/ios`)
  - url_launcher (from `.symlinks/plugins/url_launcher/ios`)

SPEC REPOS:
  trunk:
    - ACPAnalytics
    - ACPCore
    - ACPGriffon
    - ACPUserProfile
    - AppCenter
    - FMDB

EXTERNAL SOURCES:
  Flutter:
    :path: Flutter
  flutter_acpanalytics:
    :path: ".symlinks/plugins/flutter_acpanalytics/ios"
  flutter_acpcore:
    :path: ".symlinks/plugins/flutter_acpcore/ios"
  flutter_acpuserprofile:
    :path: ".symlinks/plugins/flutter_acpuserprofile/ios"
  flutter_griffon:
    :path: ".symlinks/plugins/flutter_griffon/ios"
  Instabug:
    :podspec: "./Instabug.podspec"
  instabug_flutter:
    :path: ".symlinks/plugins/instabug_flutter/ios"
  package_info:
    :path: ".symlinks/plugins/package_info/ios"
  path_provider:
    :path: ".symlinks/plugins/path_provider/ios"
  path_provider_linux:
    :path: ".symlinks/plugins/path_provider_linux/ios"
  path_provider_macos:
    :path: ".symlinks/plugins/path_provider_macos/ios"
  path_provider_windows:
    :path: ".symlinks/plugins/path_provider_windows/ios"
  sqflite:
    :path: ".symlinks/plugins/sqflite/ios"
  url_launcher:
    :path: ".symlinks/plugins/url_launcher/ios"

SPEC CHECKSUMS:
  ACPAnalytics: 10b531c3c45f665748cf81a9e18f20266097605b
  ACPCore: 5608edce9d9bdef01da9a19201993fdb144dccf8
  ACPGriffon: 53b524a9366c34968cce9b4eba50cbf72d0221d8
  ACPUserProfile: 934b0d8136dc8b4c71e95c347ae733c4482d5b9d
  AppCenter: 0487be185c038ed2ecc5ed38219af1dcd280af23
  Flutter: 0e3d915762c693b495b44d77113d4970485de6ec
  flutter_acpanalytics: 91411eff9228cd3f25b721e71f9f1052e4eee5ec
  flutter_acpcore: 781971fcbde815f237f85a4fb33539ffee53ab5d
  flutter_acpuserprofile: 97650a1a0b91dbe58ff52581445efd1eb5d90699
  flutter_griffon: fb421f3bd5459124dd09500b79fef9185e777b37
  FMDB: 2ce00b547f966261cd18927a3ddb07cb6f3db82a
  Instabug: 083ca06d54f52266ba332f352df265ed1d861210
  instabug_flutter: 33079567d70a1fa5258a04235f17ee3499a83492
  package_info: 873975fc26034f0b863a300ad47e7f1ac6c7ec62
  path_provider: abfe2b5c733d04e238b0d8691db0cfd63a27a93c
  path_provider_linux: 4d630dc393e1f20364f3e3b4a2ff41d9674a84e4
  path_provider_macos: f760a3c5b04357c380e2fddb6f9db6f3015897e0
  path_provider_windows: a2b81600c677ac1959367280991971cb9a1edb3b
  sqflite: 4001a31ff81d210346b500c55b17f4d6c7589dd0
  url_launcher: 0067ddb8f10d36786672aa0722a21717dba3a298

PODFILE CHECKSUM: 5525d91dd6c45e502723a4a692ca4f09992f63cb

COCOAPODS: 1.10.0.rc.1

**Comment by praschetan** [comment]
@vzfintechgit - we're working to update this plugin. Please stand by. FYI @PravinPK

**Comment by praschetan** [comment]
FYI. https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-experience-platform-assurance

**Comment by praschetan** [comment]
https://pub.dev/packages/flutter_assurance
