### ISSUE TITLE
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by alynaguibv** [Adobe-Marketing-Cloud/acp-sdks#445]
I'm using the latest version of the library using gradle, Can you help with this?

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=2048; index=2048 at com.android.okhttp.okio.Buffer.writeUtf8(Buffer.java:818) at com.android.okhttp.okio.Buffer.writeUtf8(Buffer.java:793) at com.android.okhttp.okio.RealBufferedSink.writeUtf8(RealBufferedSink.java:57) at com.android.okhttp.internal.http.HttpConnection.writeRequest(HttpConnection.java:172) at com.android.okhttp.internal.http.HttpTransport.writeRequestHeaders(HttpTransport.java:76) at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:786) at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:460) at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405) at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:518) at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105) at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java) at com.adobe.marketing.mobile.AndroidHttpConnection.getResponseCode(AndroidHttpConnection.java:70) at com.adobe.marketing.mobile.AudienceHitsDatabase.process(AudienceHitsDatabase.java:114) at com.adobe.marketing.mobile.AudienceHitsDatabase.process(AudienceHitsDatabase.java:32) at com.adobe.marketing.mobile.HitQueue$1.run(HitQueue.java:295) at java.lang.Thread.run(Thread.java:818)

**Comment by yangyansong-adbe** [comment]
The exception itself is not an SDK issue, I think it is likely a bug in an old version of  `okhttp` which was packaged with Android.

https://github.com/square/okhttp/issues/1776
https://github.com/square/okhttp/issues/3194

So, I also recommend trying to use the latest version of `okhttp` instead of the existing one in Android.

**Comment by shalehaha** [comment]
@alynaguibv 
Fixed in https://aep-sdks.gitbook.io/docs/release-notes#android-core-1-6-0 release, we added additional try-catch to catch all kinds of exception originated from okhttp.
