### ISSUE TITLE
Missing Swift Package support

### ISSUE THREAD

**Issue by nilsnilsnils** [Adobe-Marketing-Cloud/acp-sdks#450]
Please add swift package support

**Comment by imironchuk** [comment]
Hi @nilsnilsnils - We are working on a new Swift Core SDK that will have SPM support. Release for this will likely be in Jan.

**Comment by bordoli** [comment]
Please, we need it 😢

**Comment by Oliver-Binns** [comment]
Hi @imironchuk, is this still looking likely for Jan release? 🙂

**Comment by nilsnilsnils** [comment]
Any updates on this ?

**Comment by bencallis** [comment]
Do you have a revised ETA for this?

**Comment by Jake-Prickett** [comment]
Hello! I am also curious what the status is of SwiftPM support?

The Adobe sdks are the last step in our migration to Swift Package Manager 😅
