### ISSUE TITLE
Need to Add custom Params in Target facing Error, 2 duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by Ashishlog9** [Adobe-Marketing-Cloud/acp-sdks#457]
I am using AdobeMobileSDK', '~> 4.14.1' in my react native project . I have to  add custom parameter to Target page via mobile app . 
I am using ACPTarget and ACPCore for that but while compiling my react-native project i am facing error . Please see the log . 
Can we integrate AdobeMobileSDK and ACP Core together ?
Do we have method to add custom parameter in Target page through  AdobeMobileSDK ?
Please help me urgently , i am suffering from this issue since log time 

![Screenshot 2020-10-08 at 2 18 27 PM](https://user-images.githubusercontent.com/62419644/95436268-4647d800-0971-11eb-8fcd-cd1aa5243b5a.png)
![Screenshot 2020-10-08 at 2 19 09 PM](https://user-images.githubusercontent.com/62419644/95436280-48aa3200-0971-11eb-96e4-908dba4c5590.png)

**Comment by shalehaha** [comment]
@Ashishlog9 
You couldn't use ACP* SDK together with AdobeMobileSDK.
Not sure what parameter you wanted to add, with AdobeMobileSDK we provide the method below allows you to add several different types of parameters. You can find more info from https://docs.adobe.com/content/help/en/mobile-services/ios/target-ios/c-target-methods.html.
```
+ (void) targetLoadRequestWithName:(nullable NSString *)name
                    defaultContent:(nullable NSString *)defaultContent
                profileParameters:(nullable NSDictionary *)profileParameters
                  orderParameters:(nullable NSDictionary *)orderParameters
                   mboxParameters:(nullable NSDictionary *)mboxParameters
          requestLocationParameters:(nullable NSDictionary *)requestLocationParameters
                           callback:(nullable void (^)(NSString
                           * __nullable content))callback;
```
