### ISSUE TITLE
Duplicate Experience Cloud IDs in Campaign

### ISSUE THREAD

**Issue by syrotynin** [Adobe-Marketing-Cloud/acp-sdks#458]
Our last push messages are sent 2 times or 3 times to some customers.

We found that some registration tokens (iOS devices) were targeted during those sendouts. These are registered with same token but different Experience cloud Id (ECID) in ACS.

We don't manipulate privacy status from Mobile SDK, as it described [here](https://aep-sdks.gitbook.io/docs/using-mobile-extensions/mobile-core/identity#visitor-ids-in-apps)
_When the Mobile SDK privacy status is set to Opt-out, and the ECID is removed, a new unique visitor ID (ECID) is generated when the user sets the global privacy status to Opt-In._
 
But I have a guess - such thing could happen when we call
[Target.resetExperience](https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-target/target-api-reference#resetexperience)
 
According to the docs:
_This API resets the user's experience by removing the visitor identifiers and resetting the Target session.
Invoking this API also removes previously set Target user ID and custom visitor IDs, Target Edge Host, and the session information from persistent storage._
 
We call this method each time app is loaded to update Target with customer id later when user logged in.
 
According to[ Identity doc](https://aep-sdks.gitbook.io/docs/using-mobile-extensions/mobile-core/identity#visitor-ids-in-apps): 
_The Mobile SDK generates a unique visitor ID when the app is installed.
This ECID is stored in persistent memory on the mobile device and is sent with every hit.
The ECID is removed when the user uninstalls the app or when the user sets the Mobile SDK global privacy status to Opt-out._
 
​When I was testing, I didn't notice ECID change after calling Target.resetExperience, it was the same ECID.
Only uninstalling the app would lead to ECID change.
 
Is there a chance that resetExperience method could cause ECID regeneration at some point, maybe in a month/some period?

**Comment by emdobrin** [comment]
@syrotynin Do you mind sharing what version of ACPCore are you using? 
We did a change in ACPCore version 2.7.1 which might fix the issue you are facing. Please upgrade to this version or latest ACPCore to fetch the latest updates and fixes.

**Comment by syrotynin** [comment]
@emdobrin We were using ACPCore 2.0 as it is described on your main page: https://github.com/Adobe-Marketing-Cloud/acp-sdks.
Now we are updated to the latest version. I hope it will fix the issue. 
Thanks!

**Comment by shalehaha** [comment]
Closing inactive thread.
