### ISSUE TITLE
Equivalent of overrideConfigStream in the new SDK

### ISSUE THREAD

**Issue by omkar469** [Adobe-Marketing-Cloud/acp-sdks#461]
Hi Adobe team,

I'm trying to migrate from SDK 4.x to the new Experience platform SDK. I'm looking at this document for deprecated APIs and finding their equivalents in the new SDK https://aep-sdks.gitbook.io/docs/resources/upgrading-to-aep/api-change-log but I couldn't find anything for `Config.overrideConfigStream(stream)` (also documented [here](https://docs.adobe.com/content/help/en/mobile-services/android/configuration-android/methods.html)).

Do you have any recommendations/suggestions? Or is this functionality completely removed? 
Or is `MobileCore.configureWithFileInPath(file)` to be used going forward?

**Comment by shalehaha** [comment]
@omkar469 
Please use this API
https://aep-sdks.gitbook.io/docs/using-mobile-extensions/mobile-core/configuration#using-a-bundled-file-configuration

**Comment by omkar469** [comment]
Thank you!
