### ISSUE TITLE
iOS Adobe launch service (assets.adobedtm.com) response delay

### ISSUE THREAD

**Issue by iosmagesh18** [Adobe-Marketing-Cloud/acp-sdks#467]
We have an Adobe service call (ACPTargetRequestObject) which is being called inside the completion of the start method. 

The problem here is the request params of this service call are dependent on the "assets.adobedtm.com" response but the adobe service call (ACPTargetRequestObject) gets initiated before getting the response from "assets.adobedtm.com".

Hence, the adobe service fails and the response is nil.

[ACPCore setLogLevel:ACPMobileLogLevelDebug];
[ACPCore configureWithAppId:appKey];    
[ACPTarget registerExtension];   
[ACPAnalytics registerExtension];    
[ACPIdentity registerExtension];    
[ACPLifecycle registerExtension];    
[ACPSignal registerExtension];    
[ACPUserProfile registerExtension];    
[ACPCore start:^{        
        [ACPCore lifecycleStart:nil];

     **ACPTargetRequestObject *request = [ACPTargetRequestObject targetRequestObjectWithName:mboxName targetParameters:targetParameters  defaultContent:defaultContent callback:serviceCallback];**

}];

However, it works as expected if we add a 2/3 seconds delay before calling the adobe service call.

I am using Xcode 12.0.1, iOS 14.0.1, and below are the ACP version details,

pod 'ACPMobileServices', '~> 1.0'
pod 'ACPAudience', '~> 2.0'
pod 'ACPTarget', '~> 2.1'
pod 'ACPAnalytics', '~> 2.0'
pod 'ACPCore', '~> 2.0'
pod 'ACPUserProfile', '~> 2.0'

Kindly advise. Thanks!

Magesh M

**Comment by shalehaha** [comment]
@iosmagesh18 
can you be more specific about `the adobe service fails and the response is nil.`, which API are you referring to here?

**Comment by iosmagesh18** [comment]
@shalehaha 

I am referring to this below adobe service call,

ACPTargetRequestObject *request = [ACPTargetRequestObject targetRequestObjectWithName:mboxName targetParameters:targetParameters  defaultContent:defaultContent callback:serviceCallback];

**Comment by shalehaha** [comment]
@iosmagesh18 

I assume this issue only happens for the first launch, right?

There is a workaround where you can package a file with name `ADBMobileConfig.json` in your app's assets directory with target specific configuration.

{
"target.clientCode": "your client code",
"target.timeout": 5
}

Let me know if this helps resolve your issue.
