### ISSUE TITLE
Apple Silicon iOS Simulator Support

### ISSUE THREAD

**Issue by DavidBrunow** [Adobe-Marketing-Cloud/acp-sdks#468]
Do y'all have any timelines for when pre-built frameworks will be available that support `arm64` iOS simulators?

**Comment by ahmyr** [comment]
We are starting to look into this and will be testing against arm-based Macs once available.

**Comment by jaredmg75** [comment]
Any update on supporting arm64 iOS simulators?

**Comment by MarkPerkins** [comment]
Following

**Comment by sbenedicadb** [comment]
Hey all,

We are working on new XCFrameworks that will contain all the slices of the SDK you need.  We're very near the end of that migration, after which we will spend some time regression testing prior to release.  

Stay tuned...

-steveb

**Comment by sbenedicadb** [comment]
Hey all,

The update is live.  Please see the release notes here for more information: 

https://aep-sdks.gitbook.io/docs/release-notes#december-18-2020

Let us know if you run into any more issues.  Thanks!

-steveb
