### ISSUE TITLE
Xamarin support

### ISSUE THREAD

**Issue by inli3u** [Adobe-Marketing-Cloud/acp-sdks#48]
The legacy mobile-services repo had an SDK for Xamarin. Any plans to bring Xamarin support to the this new SDK?

**Comment by praschetan** [comment]
Hi there - yes, we've got Xamarin support planned for our new SDKs in 2019. We don't have dates as of yet. We'll post updates here https://forums.adobe.com/community/experience-cloud/platform/launch/sdk as soon as we've got more detail.
