### ISSUE TITLE
Android sdk-core 1.58 with Identity 1.2.2

### ISSUE THREAD

**Issue by takashi-aa** [Adobe-Marketing-Cloud/acp-sdks#487]
I read the release note and recognized that Android Identity 1.2.2 with sdk-core version 1.5.8 is the latest appropriate combination for using setPushIdentifier.

 https://aep-sdks.gitbook.io/docs/release-notes

However,now I have been able to retrieve Identity 1.2.2 with sdk-core 1.5.7(not 1.5.8) from the git fub.

Could it work fine?
I have the issue using setPushIdentifier and have suspected it was caused by Inappropriate combinations of Identity1.2.2 and sdk-core1.5.7.

I would like to try setPushIdentifier with sdk-core 1.5.8 as described in the release notes, could anyone update the sdk-core from 1.5.7 to 1.5.8 in the git hub repository?

**Comment by kevinlind** [comment]
Hi @takashi-aa 

The sdk-core bundle v1.5.8 contains Identity v1.2.2 and Core v1.5.7. When you add the sdk-core as a dependency to your project as `implementation 'com.adobe.marketing.mobile:sdk-core:1.5.8'`, and you enable verbose logging in your application using `MobileCore.setLogLevel(LoggingMode.VERBOSE);`, you should see the following in your logs:
```
    {
        "extensions" : {
            "Configuration" : {
                "version" : "1.5.7"
            },
            "Identity" : {
                "version" : "1.2.2"
            }
        },
        "version" : "1.5.7"
    }
```
These are the correct versions you should be seeing.

Regarding using `setPushIdentifier`, can you let us know what issues you are seeing?

**Comment by takashi-aa** [comment]
Hi @kevinlind 
Thank you for your reply.
I confirmed the log and got the same combination of each modules' version.

The issue I'm strugling is that setPushIdentifier always send ECID without registration token,
means setPushIdentifier never send registration token to ACS Server.

**Comment by kevinlind** [comment]
Hi @takashi-aa 

Can you please contact [Adobe Client Care](http://helpx.adobe.com/marketing-cloud/contact-support.html) and provide your SDK versions, SDK configuration, steps to reproduce, and verbose logs?

Thank you,
Kevin Lind

**Comment by shalehaha** [comment]
Closing inactive thread.
