### ISSUE TITLE
Access analytics payload tnta string in JSON response

### ISSUE THREAD

**Issue by mattdmpg** [Adobe-Marketing-Cloud/acp-sdks#513]
Hi there, 

I need to access the tnta analytics payload from the JSON target response for forwarding into another platform. 

I cannot see an immediate method of getting this using ACPTargetRequestObject method, which I can only return the content object from within the response.

Is there a way to access the analytics payload/tnta. Could you provide a code example?

Thanks!

**Comment by rymorale** [comment]
Hi @mattdmpg,

The Analytics for Target / tnta payload in the response is used by the SDK to automatically route data to Adobe Analytics if that is the desired reporting source. We don't support the retrieval of this payload from the Target server response.

Thanks,
Ryan Morales
Mobile Engineer
[Adobe Experience Cloud](https://www.adobe.com/experience-cloud.html)

**Comment by mattdmpg** [comment]
@rymorale  we are running Analytics out of Tealium Collect > Event Stream into Adobe Analytics Data Insertion API therefore we need the tnta to tie the 2 up for A4T.

Can this be put on the roadmap. At best this is annoying at worst you could argue its anti-competitive and forcing full adoption of the AEP SDK which is not going to be an efficient possibility for us at this time when already implemented in another data collection platform. 

Thanks!

**Comment by praschetan** [comment]
Hi @mattdmpg - supporting this request is not a priority for our roadmap at this time. Recommend working with your Adobe CSM, account reps, or partner contacts to move forward on this.
