### ISSUE TITLE
Adobe crash

### ISSUE THREAD

**Issue by pr096100** [Adobe-Marketing-Cloud/acp-sdks#514]
**START**

**Hi Team**,

We are getting below crash (counting to 114 as of now) as part of the recent release which gets reported in our firebase crashlytics, kindly help on the same to avoid these in future releases.

I have added the package used in the project along with necessary details.

Let me know in case of additional information.

**Crash** 

std::__1::__function::__func<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2, std::__1::allocator<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2>, void ()>::operator()()

**Package from podfile.lock**

- ACPAnalytics (2.4.0):
    - ACPAnalytics/main (= 2.4.0)
    - ACPCore (>= 2.5.0)
  - ACPAnalytics/main (2.4.0):
    - ACPCore (>= 2.5.0)
  - ACPAudience (2.1.0):
    - ACPAudience/iOS (= 2.1.0)
    - ACPCore (>= 2.5.0)
  - ACPAudience/iOS (2.1.0):
    - ACPCore (>= 2.5.0)
  - ACPCore (2.8.1):
    - ACPCore/main (= 2.8.1)
  - ACPCore/main (2.8.1)
  - ACPMobileServices (1.0.6):
    - ACPAnalytics (>= 2.0.3)
    - ACPCore (>= 2.1.1)
    - ACPMobileServices/iOS (= 1.0.6)
  - ACPMobileServices/iOS (1.0.6):
    - ACPAnalytics (>= 2.0.3)
    - ACPCore (>= 2.1.1)
  - ACPTarget (2.1.7):
    - ACPCore (>= 2.5.0)
    - ACPTarget/iOS (= 2.1.7)
  - ACPTarget/iOS (2.1.7):
    - ACPCore (>= 2.5.0)
  - ACPUserProfile (2.1.0):
    - ACPCore (~> 2.0)
    - ACPUserProfile/iOS (= 2.1.0)
  - ACPUserProfile/iOS (2.1.0):
    - ACPCore (~> 2.0)

**Device and OS**

99% - iPhone
1% -    iPad

85% - iOS 14
11% - iOS 13
4% - iOS 12

**Report from Firebase**

0
libsystem_kernel.dylib
__psynch_cvwait + 8
1
libsystem_pthread.dylib
_pthread_cond_wait$VARIANT$armv81 + 1180
2
libc++.1.dylib
std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 96
3
std::__1::__function::__func<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2, std::__1::allocator<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2>, void ()>::operator()() + 4343443432
4
AdobeMarketingMobile::TryCatch(std::__1::function<void ()> const&, std::__1::function<void (AdobeMarketingMobile::SdkError&)> const&) + 4343431624
5
AdobeMarketingMobile::TrySwallow(std::__1::function<void ()> const&) + 4343431448
6
void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, AdobeMarketingMobile::CreateWorkerThread(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&)::$_1> >(void*) + 4343441484
7
libsystem_pthread.dylib
_pthread_start + 288
8
libsystem_pthread.dylib
thread_start + 8

**END**

**Comment by nporter-adbe** [comment]
Hi @pr096100, I would recommend updating to the latest versions of all your extensions. The current version of ACPCore you are on is 2.5.0, which was released almost a year ago. Since then, we have made numerous fixes and performance improvements, including crash fixes that look similar to what you are experiencing.

It's hard to tell for sure if this will fix the issue described above, but I would advise you to upgrade to the latest versions and monitor for these issues in the future.

**Comment by nporter-adbe** [comment]
Hi @pr096100 could you please provide the entire crash log for the crashes you are experiencing? This will allow us to provide better investigation into this issue.

Thanks.

**Comment by pr096100** [comment]
Hi Nick Porter,

Thanks for the swift reply, much appreciated.

Sure as you suggested we will update all our ACP Packages and keep you posted if the problem gets resolved or not in the ticket after the next app release.

In the current pod files we did not mention specific version to update, expecting it should be on the latest when using pod update. So could you please confirm the latest version number for the below pods will be more helpful.


    pod 'ACPAnalytics'#, '~> 2.0'

    pod 'ACPAudience'#, '~> 2.0'

    pod 'ACPCore'#, '~> 2.0'

    pod 'ACPMobileServices'#, '~> 1.0'

    pod 'ACPTarget'#, '~> 2.0'

    pod 'ACPUserProfile'#, '~> 2.0'


Thanks & Regards,
Prithivi Raja
+61460622687

**Comment by pr096100** [comment]
Hi Nick Porter,

Currently google firebase is not providing any direct export options for individual crashes. So the only option left is to share a screen shot of the issue in a PDF.

Attached here for your investigation please let me know in case if you expect in any other formats.

Thanks & Regards,
Prithivi Raja
+61460622687

**Comment by pr096100** [comment]
Dear Nick,

Could you please help in providing the Latest version number for the pods.


Thanks & Regards,
Prithivi Raja
+61460622687

From: Prithivi Raja, (External) <prithivi.raja@vodafone.com.au>
Date: Wednesday, 6 January 2021 at 11:55 am
To: Adobe-Marketing-Cloud/acp-sdks <reply@reply.github.com>, Adobe-Marketing-Cloud/acp-sdks <acp-sdks@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: Re: [Adobe-Marketing-Cloud/acp-sdks] Adobe crash (#514)
Hi Nick Porter,

Currently google firebase is not providing any direct export options for individual crashes. So the only option left is to share a screen shot of the issue in a PDF.

Attached here for your investigation please let me know in case if you expect in any other formats.

Thanks & Regards,
Prithivi Raja
+61460622687

**Comment by nporter-adbe** [comment]
I do not see any crash report attached to any of your messages. If you are replying to the email and attaching it there I don't think github supports that functionality.

For the latest versions please see: https://aep-sdks.gitbook.io/docs/resources/upgrading-to-aep/current-sdk-versions

**Comment by pr096100** [comment]
[Adobe Crash.pdf](https://github.com/Adobe-Marketing-Cloud/acp-sdks/files/5784397/Adobe.Crash.pdf)

Thanks Nick, attached here.

**Comment by nporter-adbe** [comment]
The PDF attached doesn't appear to contain much more information than what is already posted above. Could you gather the full crash information and reach out to the [customer care](https://helpx.adobe.com/marketing-cloud/contact-support.html) and open a ticket. 

Thanks.

**Comment by addb** [comment]
@pr096100 Were you abel to resolve the issue? If you still need help, please open a ticket with [Client Care](https://experienceleague.adobe.com/?support-solution=General#support)
