### ISSUE TITLE
ld: library not found for -laCPAnalytics_iOS

### ISSUE THREAD

**Issue by kishore94** [Adobe-Marketing-Cloud/acp-sdks#515]
When I try to run for Mac I am getting this error "ld: library not found for -laCPAnalytics_iOS" 

I am using   pod 'ACPAnalytics', '~> 2.5.0' this version support m1 architecture I believe , please point out where I am missing thanks

**Comment by sbenedicadb** [comment]
Hey @kishore94 -

Can you please provide a sample project that produces this error?  

The message indicates that your project is trying to link the Analytics library, which is expected for installation method via Cocoapods.

Thanks.

-steveb

**Comment by kishore94** [comment]
@sbenedicadb  here is the demo project run it for Mac 

https://drive.google.com/file/d/1Katdgp-j-Chky4X40chXy82i0Mqgg8Dt/view?usp=sharing

**Comment by shalehaha** [comment]
@kishore94 

Currently, the M1 support we provide is only for iOS/Watch/tvOS simulators, we don't support native Mac apps yet.

Please contact [Adobe Client Care](http://helpx.adobe.com/marketing-cloud/contact-support.html)  to raise a feature request if you need this support, then we can prioritize it.

Thanks,
Jiabin
