### ISSUE TITLE
[Question] How do I create custom state in media sdk? 

### ISSUE THREAD

**Issue by nishantkp** [Adobe-Marketing-Cloud/acp-sdks#520]
From this documentation, there are like 5 out of box states
https://experienceleague.adobe.com/docs/media-analytics/using/player-state-tracking/standard-and-custom-states.html?lang=en#guidelines and https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-media-analytics/media-api-reference#player-state-constants

How do I create a custom state?
If I start the state with `StateStart`, do I have to complete it with `StateEnd`?

**Comment by addb** [comment]
@nishantkp 

Create custom state by passing your desired state name as String to` createStateObject` API 
```
HashMap<String, Object> stateObject = Media.createStateObject("YOUR_CUSTOM_STATE");
```

Refer: https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-media-analytics/media-api-reference#createstateobject

To start and complete a state like this:
```
// StateStart
  HashMap<String, Object> stateObject = Media.createStateObject("YOUR_CUSTOM_STATE");
  _tracker.trackEvent(Media.Event.StateStart, stateObject, null);

// StateEnd
  HashMap<String, Object> stateObject = Media.createStateObject("YOUR_CUSTOM_STATE");
  _tracker.trackEvent(Media.Event.StateEnd, stateObject, null);
```

Refer: https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-media-analytics/media-api-reference#trackevent-2

**Comment by nishantkp** [comment]
Hi @addb,

Is it ok if I don't end the state or is it absolutely necessary to end it?

**Comment by addb** [comment]
If you want to track the state for the **entire session** then it's fine to just have `StateStart` and it will be closed on the backend side when it gets `sessionEnd`/`complete` events.
