### ISSUE TITLE
[Android] Unable to attach metadata value on StateStart event 

### ISSUE THREAD

**Issue by nishantkp** [Adobe-Marketing-Cloud/acp-sdks#522]
Hi, 

I need to track context data `(video.binge)` on the state start.

I am creating a custom state and adding a metadata like this,

```java
HashMap<String, String> bingeWatchMetaData = new HashMap<>();
bingeWatchMetaData.put("video.binge", "1");
HashMap<String, Object> bingeWatchState = Media.createStateObject("bingeWatch");
mediaTracker.trackEvent(Media.Event.StateStart, bingeWatchState, bingeWatchMetaData);
```

ADB logs looks like this,

```java
02-10 14:48:10.919 15920-15959/ V/AdobeExperienceSDK: EventBus(EventHub) - Processing event #67: {
        class: Event,
        name: Media::TrackMedia,
        eventNumber: 67,
        uniqueIdentifier: d43c9982-4b79-429d-8254-b9ffeb03b4d7,
        source: com.adobe.eventsource.media.trackmedia,
        type: com.adobe.eventtype.media,
        pairId: null,
        responsePairId: 95b9b8a7-916c-4186-aa5c-25c5555af8f3,
        timestamp: 1612986490919,
        data: {
            "event.timestamp" : 1612986490919,
            "event.metadata" : {
                "video.binge" : "1"
            },
            "event.param" : {
                "state.name" : "bingeWatch"
            },
            "event.internal" : false,
            "event.name" : "statestart",
            "sessionid" : "960564af-975b-4e09-80f4-77c89c5f6b63",
            "trackerid" : "2716c8d9-d902-4458-a972-18962ca55cd2"
        }
    }
```

But when I look into Charles it looks like this,

```json
{
  "eventType": "stateStart",
  "playerTime": {
    "playhead": 0,
    "ts": 1612986490919
  },
  "params": {
    "media.state.name": "bingeWatch"
  }
}
```

There is no metadata value in here and only the state name is.
Why is that? Am I doing it incorrectly?

**Comment by addb** [comment]
@nishantkp metadata is not supported currently with player state tracking. You can just `start` and `end` a State. 

More on Player State Tracking: https://experienceleague.adobe.com/docs/media-analytics/using/player-state-tracking/player-state-overview.html?lang=en#requirements

**Comment by nishantkp** [comment]
@addb I see,  If I want to count the instances for the state, how would I do that?

**Comment by addb** [comment]
@nishantkp that will be available on the reporting side refer: https://experienceleague.adobe.com/docs/media-analytics/using/player-state-tracking/implementation-and-reporting.html?lang=en#reporting

**Comment by nishantkp** [comment]
After setting up the state name on the reporting side, it works perfectly. You can close the ticket.

Thanks a bunch, @addb !
