### ISSUE TITLE
Manual iOS Installation

### ISSUE THREAD

**Issue by simon-o** [Adobe-Marketing-Cloud/acp-sdks#526]
Hi, I struggle to install ACPCore and ACPAnalytics. I follow the instruction, but something is missing for sure, could you update it and make it more clear to ease the installation please.

**Comment by shalehaha** [comment]
@simon-o 

Could you please provide some more details regarding the problem you ran into? So we know where we should start in order to help you.

Thanks,
Jiabin

**Comment by simon-o** [comment]
I imported the framework into my project, everything is linked properly but when I try to import the .h into the bridge I can't manage to find APCCore.h to use it in Swift.

**Comment by shalehaha** [comment]
@simon-o You should be able to import it by using `#import "ACPCore.h"`. 
https://github.com/nporter-adbe/manual-install-acp, this is a quick sample app showing that.

**Comment by simon-o** [comment]
I had to extract the header from the framework and it worked great, not sure it is a "legit" method

**Comment by shalehaha** [comment]
@simon-o 
Please have a look at the updated XCFrameworks in the [maps branch](https://github.com/Adobe-Marketing-Cloud/acp-sdks/tree/maps/iOS).  We've manually included a `module.modulemap` for each of the distribution slices.  From our local testing, everything seems to be working nicely.  

We'd like some help from you in validating the solution in your environments. If things look good, we'll update our deployment scripts to ensure that all future builds for manual installation include the correct modulemap files.

Thanks for your help and patience.

**Comment by shalehaha** [comment]
@simon-o 
Closing the ticket, more info can be found from the thread https://github.com/Adobe-Marketing-Cloud/acp-sdks/issues/525.
