### ISSUE TITLE
Release 1.7.0 is breaking all builds

### ISSUE THREAD

**Issue by gotev** [Adobe-Marketing-Cloud/acp-sdks#531]
This release https://search.maven.org/artifact/com.adobe.marketing.mobile/sdk-core/1.7.0/pom is actually breaking builds, because it's searching for non existing 1.7.0 versions of the other components, which are not released yet: https://search.maven.org/search?q=g:com.adobe.marketing.mobile

We followed this instructions: https://github.com/Adobe-Marketing-Cloud/acp-sdks#installing-the-aep-sdk-for-android

This happens because versions are not locked at all. Maybe it will be better to lock them and update the readme regularly as new releases comes out and after proper testing.

**Comment by gotev** [comment]
For anyone else experiencing this problem, it's sufficient to fix sdk-core version.

```
    // Adobe Launch
    implementation 'com.adobe.marketing.mobile:sdk-core:1.6.0'
    implementation 'com.adobe.marketing.mobile:analytics:1.+'
    implementation 'com.adobe.marketing.mobile:audience:1.+'
    implementation 'com.adobe.marketing.mobile:target:1.+'
    implementation 'com.adobe.marketing.mobile:userprofile:1.+'
    implementation 'com.adobe.marketing.mobile:media:1.+'
```

**Comment by shalehaha** [comment]
Seems like there was a delay when syncing the artifact to maven. It should be good now.
