### ISSUE TITLE
tvOS support for ACP (ACPMedia and ACPAnalytics)

### ISSUE THREAD

**Issue by rshortall** [Adobe-Marketing-Cloud/acp-sdks#532]
I'm trying to add ACP support to my tvOS project but I'm getting linking errors regarding ACPMedia and ACPAnalytics. The app is targeting tvOS 13.2 and I'm using XCode 12.3. My podfile has the following:

    pod 'ACPCore', '~> 2.9.1'
    pod 'ACPMedia', '~> 2.3.0'
    pod 'ACPAnalytics', '~> 2.5.0'

When I try and compile I get the following:

Undefined symbols for architecture arm64:
     "_OBJC_CLASS_$_ACPMedia", referenced from:
           __OBJC_$_CATEGORY_ACPMedia_$_ForceLoad in ACPMedia(Empty.o)
     "_OBJC_CLASS_$_ACPAnalytics", referenced from:
           __OBJC_$_CATEGORY_ACPAnalytics_$_ForceLoad in ACPAnalytics(Empty.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Are these supported in tvOS or perhaps I'm using the wrong versions?

**Comment by sbenedicadb** [comment]
Hey @rshortall,

I tried in a local app with the following `podfile` and didn't have any issues:

```
target 'tvXcframworkTester' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tvXcframworkTester
  pod 'ACPCore', '~> 2.9.1'
  pod 'ACPAnalytics', '~> 2.5.0'
  pod 'ACPMedia', '~> 2.3.0'

end
```

Do you have `use_frameworks!` commented?  

The XCFramework versions specified have arm64 support for both device and simulator.

If this doesn't work, would you mind sharing a sample app that reproduces the issue?  Thanks.

-steveb

**Comment by rshortall** [comment]
Apologies, I should have created a sample app myself to begin with! (the sample tvOS app worked fine)

It's now working for me for my original app though I'm a bit confused. I had initially added these pods to the iOS section of the podfile and then added them to a shared section later (to work on tvOS) and it was failing to install them for tvOS properly after runnig 'pod install'. 

Removing them from the podfile completely, running 'pod install', and then adding them back in to the shared section has now resulted in them being correctly added for iOS and tvOS.

Sorry and thanks for your help!
