### ISSUE TITLE
iOS ACPCore collectLaunchInfo does nothing

### ISSUE THREAD

**Issue by bugoriy** [Adobe-Marketing-Cloud/acp-sdks#538]
Hi, I'm trying to track that user launched the app through notification click. I tried to debug, this code is being called but it doesn't send any HTTP request and I don't see user clicks on dashboard.
I refer to this [documentation](https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-analytics-mobile-services#set-up-push-tracking)

Note: ACPCore.start and registration of others extension called in `application didFinishLaunchingWithOptions`
```
    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                didReceive response: UNNotificationResponse,
                                withCompletionHandler completionHandler: @escaping () -> Void) {
        logInfo(description: response.debugDescription, domains: [.userAction])
        // Required: tell the MarketingCloudSDK about the notification. This will collect MobilePush analytics
        // and process the notification on behalf of your application.
        MarketingCloudSDK.sharedInstance().sfmc_setNotificationRequest(response.notification.request)
        applicationCoordinator.handlePushNotificationDeeplink(response: response)
        if UIApplication.shared.applicationState != .active {
            ACPCore.collectLaunchInfo(response.notification.request.content.userInfo)
        }
        completionHandler()
    }

**Comment by shalehaha** [comment]
@bugoriy 

Can you give me the list of all the extensions you have installed? And the code you are using to init the SDK.
Also, it would be helpful if you can enable the verbose logging of SDK and provide the full console log.

Thanks,
Jiabin

**Comment by bugoriy** [comment]
Hi @shalehaha, here you go

```
    func setUpAnalytics(_ completion: @escaping (String?) -> Void) {
        ACPCore.configure(withAppId: serviceLayer.configurator.getEnvironmentConfig().adobeEnvironmentID)
        ACPUserProfile.registerExtension()
        ACPLifecycle.registerExtension()
        ACPSignal.registerExtension()
        ACPGriffon.registerExtension()
        ACPCampaignClassic.registerExtension()
        ACPAnalytics.registerExtension()
        ACPTarget.registerExtension()
        ACPIdentity.registerExtension()
        
        ACPCore.start { [weak self] in
            ACPCore.lifecycleStart(nil)
            self?.getCloudID()
                .retry(upTo: AnalyticsConst.kMidRepeatCount,
                       when: { (error) -> Bool in
                    return error != .emptyMid
                })
                .startWithResult({ result in
                    if case .success(let mid) = result {
                        completion(mid)
                        self?.isStarted = true
                    }
                })
        }
    }
    ```
    pod 'ACPAnalytics', '2.2.4', :binary => true
    pod 'ACPGriffon', '1.2.0', :binary => true
    pod 'ACPCampaignClassic', '2.0.2', :binary => true
    pod 'ACPCore', '2.8.0', :binary => true
    pod 'ACPTarget', '2.1.5', :binary => true
    pod 'ACPUserProfile', '2.0.1', :binary => true
    
Thanks

**Comment by bugoriy** [comment]
Hi @shalehaha, could you check the message above?
thanks

**Comment by shalehaha** [comment]
@bugoriy 
You need to install the Mobile Services extension to get it working. Docs: https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-analytics-mobile-services#configure-the-mobile-services-extension-in-experience-platform-launch

**Comment by bugoriy** [comment]
Thanks @shalehaha, your suggestion solved the problem!
