### ISSUE TITLE
Manual xcframeworks installation does not work

### ISSUE THREAD

**Issue by frederik-jacques** [Adobe-Marketing-Cloud/acp-sdks#546]
Hi all,

I have tried to implement the ACP SDK for iOS, but I can't get it to work by following the steps described in the README file.
I've created a repository with the most simple setup for you to check at https://github.com/frederik-jacques/adobe-sdk-sandbox .

I need to use 3 SDKs:
- ACPCore
- ACPAnalytics
- ACPMobileServices

Steps I have done as explained in the README file:
- Drag the xcframework files to Xcode
- Verify that these are in the list of `Link binary with libraries`
- Add UserNotifications, Webkit, SystemConfiguration, UIKit, libz, libc++, libsqlite3.0 frameworks
- Try to call ACPAnalytics or whatever framework, but to no avail

I'm using Xcode 12.4.
I hope you can guide me on what I am doing wrong.

Kind regards,
Frederik

**Comment by nporter-adbe** [comment]
Hi @frederik-jacques, sorry to hear you've had issues linking the libraries manually. One step you may need to do is ensure that you have imported the libraries in your bridging header. After that, you should have access to the APIs throughout your app.

Here is a repo that demonstrates the manual install: https://github.com/nporter-adbe/manual-install-acp

Let us know if you continue to face issues.

**Comment by nporter-adbe** [comment]
I forked your example repo and made the required changes to get it working: https://github.com/nporter-adbe/adobe-sdk-sandbox/commit/d2a26e516a22c93c58ed23b11d83aa073b1e58fd

**Comment by frederik-jacques** [comment]
Hi @nporter-adbe,

Thank you so much for your quick response, and indeed it works!
So now I tried to implement it in our app, but there i still get errors.

I've created another test repository (https://github.com/frederik-jacques/adobe-workspace) where I mirrored the most basic structure of our app.

Workspace
 - Main app
 - FrameworkA (TNOther)
 - FrameworkB (TNTagger)
 - - Adobe Framework

So the difference with the previous repo is that we want to embed the Adobe frameworks within a specific framework and not in the app. We have a "Tagging" framework which can be linked in our different apps.

When I add the Adobe framework to the header file of the TNTagger framework (TNTagger.h), I get an error `Include of non-modular header inside framework module 'TNTagger'`.
Could you help me figure out what I'm missing?

Kind regards,
Frederik

**Comment by nporter-adbe** [comment]
Hi @frederik-jacques, this isn't currently a well-supported workflow. The best approach I can suggest is to take a look at the libraries in the maps branch. We've manually included a module.modulemap for each of the distribution slices. From our local testing, everything seems to be working nicely.

We are still experimenting with including a modulemap with our libraries, but you could follow this approach then import the Analytics extension as `import ACPAnalytics`.

I've forked your repo and made the changes for the Analytics extension. https://github.com/nporter-adbe/adobe-workspace/commit/a0e37c6942c7a6ccc4caa753021994fd8a838dcf

You can find a branch with the libraries containing modules maps here: https://github.com/Adobe-Marketing-Cloud/acp-sdks/tree/maps

Please note these haven't been updated with the latest libraries, so you may need to add these modulemaps yourself.

**Comment by frederik-jacques** [comment]
Hi @nporter-adbe ,

Thanks for your help, I have added the module maps to the different frameworks based on the /maps branch.
Although now I have an issue where we are unable to build.
The ProcessXCFramework script gives an error that there is a duplicate file (.DS_Store).
Deleting the .DS_Store file does not work, as it is automatically recreated a few seconds after you delete it.

<img width="1085" alt="CleanShot 2021-04-22 at 15 50 40@2x" src="https://user-images.githubusercontent.com/1405568/115725900-85280300-a382-11eb-862c-e1e113315a55.png">

The weird thing however, is that when I manually copy over the header files to the build output directory, it does work.
But of course, this is not a solution that is sustainable.

I guess this is more an issue with Xcode's build system, but still wanted to share this issue, or maybe you have an idea what is going on.

Kind regards,
Frederik

**Comment by nporter-adbe** [comment]
@frederik-jacques that's an interesting error, one that I haven't run into before. Thanks for sharing that.

Since it sounds like you've been able to resolve your issues I'm going to close this issue, feel free to re-open if the issue persists.
