### ISSUE TITLE
iOS Using Adobe Launch xcframework in Framework target with Swift code files

### ISSUE THREAD

**Issue by wshrads** [Adobe-Marketing-Cloud/acp-sdks#555]
I have integrated Adobe Launch XCFrameworks in Application target in XCode. After importing Adobe classes in Bridging Header, I am able to call the Adobe Launch APIs from swift code successfully. However, if I create a Framework target in Xcode and add, link the Adobe Launch xcframeworks in build phases of the framework target and import the Adobe classes in universal header file, I am getting an error : Include of non-modular header inside framework module.

How can I use Adobe Launch XCFrameworks in framework targets in swift code files ? Note that using Adobe Launch XCFrameworks in framework targets works with objective C files as we can import the Adobe Launch class headers in .m files.

**Comment by shalehaha** [comment]
@wshrads 
This is a duplicated issue of https://github.com/Adobe-Marketing-Cloud/acp-sdks/issues/525, please follow that thread to get updated info.
