### ISSUE TITLE
Missing required modules error in app target when using umbrella framework with ACP Modules

### ISSUE THREAD

**Issue by wshrads** [Adobe-Marketing-Cloud/acp-sdks#563]
Hi,

I created an umbrella framework in swift by using ACPCore and other related modules. However, I am not able to import the umbrella framework successfully in application target. I am getting compilation errors in swift files in the app target which is  :
Missing required modules: 'ACPAnalytics', 'ACPCore', 'ACPIdentity', 'ACPLifecycle', 'ACPSignal', 'ACPUserProfile'

Note that if I create the same umbrella framework with objective C, everything works fine.

**Comment by shalehaha** [comment]
@wshrads 
Is this the same problem as https://github.com/Adobe-Marketing-Cloud/acp-sdks/issues/555? We have added the modulemaps to the xcframeworks in the master branch, so you can get them from there.

If this is a different problem, can you please provide a sample project showing what you are trying to do?

Thanks,
Jiabin

**Comment by wshrads** [comment]
Yes same problem. Validated that it works fine with module maps. Posted this question because we use SDKs from releases rather than downloading it from master for our app releases. Thus asking if you have any planned date on when the next release will be available with this fix, so that we can align our app release accordingly.

**Comment by shalehaha** [comment]
you mean you are getting the builds from https://github.com/Adobe-Marketing-Cloud/acp-sdks/releases?

**Comment by wshrads** [comment]
Yes

**Comment by wshrads** [comment]
I have another issue using the ACP frameworks in umbrella framework. I am using Xcode 12.4 with deployment target 11.0.

I created a swift based framework. I added all the ACP xcframeworks to this umbrella framework. Created a swift class in this framework to use ACPCore methods to trackAction and trackState. Built this umbrella framework successfully into a .framework using lipo command. 
However, when I use this umbrella framework in my ObjC+Swift based Application, all the swift classes using this framework are having compilation errors while Archiving in release mode.

I get this error :
Missing required modules: 'ACPAnalytics', 'ACPCore', 'ACPIdentity', 'ACPLifecycle', 'ACPSignal', 'ACPUserProfile'

Note that - if I just compile and run the same setup in debug mode, all works well. Am I missing any additional step during archiving ?

**Comment by shalehaha** [comment]
@wshrads 
The binaries you got from the releases are for cocoapods, so the structure is a little bit different from what we have in the master branch. So it'd be better if you can pull the SDKs from the master branch.

Regarding your second question, I'm not sure how you set up the umbrella framework, but can you check whether the SDKs are embedded in the umbrella framework, or embedded in the app during compilation. Still, if you can give us a sample project, it will be much easier for us to help.

**Comment by wshrads** [comment]
Hi, I invited you to the sample project I created [here](https://github.com/wshrads/Demo). Code available in master branch.
I have created an XCFramework out of ACPs XCFrameworks and trying to use it in the demo app. The objective C code works well with the umbrella framework, however the swift classes are not compiling and erroring for all ACP frameworks.

**Comment by shalehaha** [comment]
@wshrads 
If you want to totally hide ACP* frameworks inside `DemoFramework`, one option is to use `@_implementationOnly` when importing ACP* libs. This way, all the ACP* won't show up in the module interface.
```
@_implementationOnly import ACPCore
@_implementationOnly import ACPSignal
@_implementationOnly import ACPAnalytics
@_implementationOnly import ACPIdentity
@_implementationOnly import ACPLifecycle
@_implementationOnly import ACPUserProfile
```

I'm not sure why you want to build xcframework for `DemoFramework` and then import it into the app, but if you can different include the `DemoFramework` target in your app, xcode should be able to properly handle things for you.

Let me know whether it helps. Thanks.

**Comment by wshrads** [comment]
Thanks @shalehaha. I will try this. I am recently migrating to Adobe Launch. Earlier I was using the static library explicitly provided in Adobe Mobile libraries suite to track events in app extensions like Notification, Widgets etc. The reason for building a separate umbrella framework with ACP libs is to re-use the umbrella framework in app extensions targets. I hope with this approach I can re-use ACP tracking in app extensions. Let me know if there is a better way.

**Comment by shalehaha** [comment]
@wshrads 
I understand your purpose of having a shared framework, but my question is more on why you want to manually build an xcframework instead of just including the shared Target in your app's Target.

Also, it's worth noting that we currently don't officially support iOS app extensions yet.

**Comment by wshrads** [comment]
@shalehaha Got your point. I will add the shared framework target in app project. 
Also, it would help if you keep us posted when adobe launch officially starts supporting iOS app extensions.

**Comment by shalehaha** [comment]
@wshrads 
We won't be supporting app extensions with this version of SDKs. But keep an eye on https://github.com/adobe/aepsdk-core-ios, however, app extension support is a low priority for us, so there is no ETA I could share right now.
