### ISSUE TITLE
Sdk Tracking Activity bundle Data

### ISSUE THREAD

**Issue by r0shanbhagat** [Adobe-Marketing-Cloud/acp-sdks#569]
Recenlty i integrated the AEP SDK in Android , i see the AEP sdk is collecting **activities bundle's data** which i'm passing from one **activity** to another. I want to prevent this tracking ? Please let me know how to handle this.
Please check the **logs** for more reference:
AdobeExperienceSDK: **Core - collectData: generic data OS event dispatched.**
AdobeExperienceSDK: EventBus(EventHub) - Processing event #32: {
class: Event,
name: CollectData,
eventNumber: 32,
source: com.adobe.eventsource.os,
type: com.adobe.eventtype.generic.data,
pairId: null,
timestamp: 1621421190625,
**data: {
"Name" : "John"
"Email" : "john@testmail.com"
}**
}

**Comment by sbenedicadb** [comment]
Hey @r0shanbhagat - 

Can you please clarify your concern?  The log you shared shows an Event being processed, which is foundational for allowing SDK extensions to communicate with one another.  I'm also not seeing any bundle data in this log.  

Thanks.

-steveb

**Comment by wshrads** [comment]
@sbenedicadb -> The concern is that everything stored in the Activity bundle is getting sent in this collect data event. Activity bundles may include PII data. Is there a way to prevent the activity bundle from being passed to the collect data event? Like in this case, if we do not want to send the data "Name" and "Email" to the SDK? 

AdobeExperienceSDK: EventBus(EventHub) - Processing event #32: {
class: Event,
name: CollectData,
eventNumber: 32,
source: com.adobe.eventsource.os,
type: com.adobe.eventtype.generic.data,
pairId: null,
timestamp: 1621421190625,
**data: {
"Name" : "John"
"Email" : "john@testmail.com"
}**
}

**Comment by sbenedicadb** [comment]
@r0shanbhagat the SDK does not collect this data automatically - it is a result of an SDK API call being made.  What API are you calling to initiate this Event, and where are you calling it?  

Thanks.

-steveb

**Comment by wshrads** [comment]
@sbenedicadb -> We registered following extensions in TestApplication.java which extends Application

MobileCore.setApplication(TestApplication.getAppInstance());
            Analytics.registerExtension();
            Identity.registerExtension();
            Lifecycle.registerExtension();
            Signal.registerExtension();
            UserProfile.registerExtension();

            MobileCore.start(o -> {
                MobileCore.configureWithAppID(mAppId); // App Id for the app
            });



And then we are calling the below methods in all the Activity classes which extend AppCompatActivity.

protected void onResume() {
        super.onResume();
        **MobileCore.setApplication(AmeripriseClientApplication.getAppInstance());
        MobileCore.lifecycleStart(null);**
}

@Override
    protected void onPause() {
        **MobileCore.lifecyclePause();**
        super.onPause();
    }

**Comment by wshrads** [comment]
@sbenedicadb -> As per the recommendation in here : https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-target

The SDK can only collect information from the launching Activity if setApplication has been called. Setting the Application is only necessary on an Activity that is also an entry point for your application. However, setting the Application on each Activity has no negative impact and ensures that the SDK always has the necessary reference to your Application. We recommend that you call setApplication in each of your Activities.

We registered following extensions in TestApplication.java which extends Application

MobileCore.setApplication(TestApplication.getAppInstance());
            Analytics.registerExtension();
            Identity.registerExtension();
            Lifecycle.registerExtension();
            Signal.registerExtension();
            UserProfile.registerExtension();

            MobileCore.start(o -> {
                MobileCore.configureWithAppID(mAppId); // App Id for the app
            });

And then we are calling the below methods in all the Activity classes which extend AppCompatActivity.

protected void onResume() {
        super.onResume();
        MobileCore.setApplication(TestApplication.getAppInstance());
        MobileCore.lifecycleStart(null);
}

@Override
    protected void onPause() {
        MobileCore.lifecyclePause();
        super.onPause();
    }

**Comment by sbenedicadb** [comment]
Hey @wshrads - 

I see what you're saying.  Let me chat with a few folks and get back with you on this...

Thanks.

-steveb

**Comment by wshrads** [comment]
@sbenedicadb 
Can you please let us know if there are any updates as the reported issue is a blocker for us.

**Comment by sbenedicadb** [comment]
Hey @wshrads -

It's not clear to me what the concern is about the event going through the eventHub.  I can tell you that from an internal perspective, we only use these events when they contain a specific kind of data (to automatically handle deeplink and notification clickthroughs).  Other than that, the event will just fall on the ground, as there are no other listeners doing anything with the data (e.g. - it doesn't result in any network requests leaving the device).  

Can you help me better understand the concern?  Thanks.

-steveb

**Comment by wshrads** [comment]
The concern is that we see iall the bundle parameters were being sent to the AdobeExperienceSDK events. As long as the SDK only uses only specific bundle parameters for automatically handling deeplink and notification clickthroughs and does not send any other bundle parameters to the console, we are good.

**Comment by sbenedicadb** [comment]
Sounds good - going to close this one out.
