### ISSUE TITLE
ACPTarget | prefetchContent()

### ISSUE THREAD

**Issue by vijayajay17** [Adobe-Marketing-Cloud/acp-sdks#577]
Hi Team, 

We are migrating from 4x to new Exp.. platform SDK and one of the method which got deprecated we are trying to replace it with is as below

In 4x SDK, We used method

let request = ADBMobile.targetCreateRequest(withName: "requestName", defaultContent: content, parameters: [:]) 
ADBMobile.targetLoad(request) { response in
//// response was used for further functions
}

Right now we believe we need to use the ACPTarget framework in the Experience Platform SDK to do the same as below

let targetProduct = ACPTargetProduct(id: "", categoryId: "")
let targetOrder = ACPTargetOrder(id: "", total: 0, purchasedProductIds: [""])
let targetParams = ACPTargetParameters(parameters: [:], profileParameters: [:], product: targetProduct, order: targetOrder)
let req = ACPTargetPrefetchObject(name: "", targetParameters: targetParams)
ACPTarget.prefetchContent([req], with: targetParams) { (error) in
}

Since the callback is just returning the error, Is there a method or a way to get the response back in callback?

**Comment by swarna04** [comment]
@vijayajay17 Thank you for reaching out. The equivalent of Target load request v4.x SDK API
```
+ (void) targetLoadRequest:(nullable ADBTargetLocationRequest *)request 
                                 callback:(nullable void (^)(NSString* __nullable content))callback;
```
in v5 2.x ACPTarget SDK is
```
+ (void) retrieveLocationContent: (nonnull NSArray<ACPTargetRequestObject*>*) requests
                            withParameters: (nullable ACPTargetParameters*) parameters;
```
You can find more information on the same in sdk docs [Target API reference - retrievelocationcontent](https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-target/target-api-reference#retrievelocationcontent)
Please feel free to reach out if you have further questions.

--
Swarna Saraf

**Comment by NareshJain91** [comment]
@swarna04 

retrieveLocationContent method doesn't have a callback. We need callback String which we were getting in targetLoadRequest.

Thats callback String we send it to our server

**Comment by rymorale** [comment]
Hi @NareshJain91, each `ACPTargetRequestObject` within the requests passed to the `retrieveLocationContent` API contains a callback. A usage example is provided in the link @swarna04 provided in her reply:
```swift
let mboxParameters1 = [
"status": "platinum"
]
let product1 = ACPTargetProduct(id: "24D3412", categoryId: "Books")
let order1 = ACPTargetOrder(id: "ADCKKIM", total: NSNumber(value: 344.30), purchasedProductIds: ["a", "b"])

let mboxParameters2 = [
"userType": "Paid"
]
let product2 = ACPTargetProduct(id: "764334", categoryId: "Online")
let order2 = ACPTargetOrder(id: "4t4uxksa", total: NSNumber(value: 54.90), purchasedProductIds: ["id1", "id2"])
 let params1 = ACPTargetParameters(parameters: mboxParameters1, profileParameters: nil, product: product1, order: order1)
let request1 = ACPTargetRequestObject(name: "logo", targetParameters: params1, defaultContent: "BlueWhale", callback: { content in
// do something with the received content
})

let params2 = ACPTargetParameters(parameters: mboxParameters2, profileParameters: nil, product: product2, order: order2)
let request2 = ACPTargetRequestObject(name: "logo", targetParameters: params2, defaultContent: "red", callback: { content in
// do something with the received content
})

// Create request object array
let requestArray = [request1, request2]

// Creating Target parameters
let mboxParameters = [
"status": "progressive"
]
let profileParameters = [
"age": "20-32"
]
let product = ACPTargetProduct(id: "24D334", categoryId: "Stationary")
let order = ACPTargetOrder(id: "ADCKKBC", total: NSNumber(value: 400.50), purchasedProductIds: ["34", "125"])

let targetParameters = ACPTargetParameters(parameters: mboxParameters, profileParameters: profileParameters, product: product, order: order)

// Call the API
ACPTarget.retrieveLocationContent(requestArray, with: targetParameters)
```
Thanks,
Ryan

**Comment by vijayajay17** [comment]
Hi @rymorale ,

We are integrating the swift version and below is the callback code we tried

func targetCreateRequest() {
  let targetParams = TargetParameters.init(parameters: ["id":"1234"], profileParameters: nil, order: nil, product: nil)
  let targetRequest = TargetRequest.init(mboxName: "name", defaultContent: "content", targetParameters: targetParams) { (result) in 
    //// Somehow the control never hits the callback
}

Is there something im missing?

Thanks & regards
Vijay

**Comment by rymorale** [comment]
Hi @vijayajay17,
Can you share more of your code including the call to ACPTarget.retrieveLocationContent? If you are able to provide some debug log output that would be helpful as well. The call to retrieveLocationContent should at least have a result containing the default content specified in the Target Request.

Thanks,
Ryan

**Comment by rymorale** [comment]
Hi @vijayajay17,

I took a look at the code provided and made some slight changes to get it working. Give this a try:
```swift
// call to retrieveLocationContent (equivalent to loadRequest)
let request = targetCreateRequest()
Target.retrieveLocationContent([request])

 func targetCreateRequest() -> TargetRequest {
        let targetParams = TargetParameters.init(parameters: ["id":"1234"], profileParameters: nil, order: nil, product: nil)
        let targetRequest = TargetRequest.init(mboxName: "name", defaultContent: "content", targetParameters: targetParams) 
       { (result) in
            print(result)
        }
        return targetRequest
    }
```

**Comment by NareshJain91** [comment]
@rymorale 

While using the above code we are getting the below error

```
expression produced error: error: virtual filesystem overlay file '/Users/abcd/Library/Developer/Xcode/DerivedData/AEPCore-hitruxktrhfcygasuurgsqerciki/Build/Intermediates.noindex/ArchiveIntermediates/AEP-All/IntermediateBuildFilesPath/AEPCore.build/Release-iphonesimulator/AEPCore.build/all-product-headers.yaml' not found

error: couldn't IRGen expression. Please check the above error messages for possible root causes.
```

**Comment by rymorale** [comment]
@NareshJain91 are the AEPSDK frameworks being imported into the app? I noticed that they weren't in the provided sample app. Can you provide a sample which matches your current app setup as close as possible?

Thanks,
Ryan

**Comment by NareshJain91** [comment]
Hi 

Here is a sample app - https://drive.google.com/file/d/1-CAleyZQa8KeQTfuPn0Q57lFanyyU6bt/view?usp=sharing

Below is the error we are getting

```
expression produced error: error: virtual filesystem overlay file '/Users/abcd/Library/Developer/Xcode/DerivedData/AEPCore-hitruxktrhfcygasuurgsqerciki/Build/Intermediates.noindex/ArchiveIntermediates/AEP-All/IntermediateBuildFilesPath/AEPCore.build/Release-iphonesimulator/AEPCore.build/all-product-headers.yaml' not found

error: couldn't IRGen expression. Please check the above error messages for possible root causes.
```

**Comment by vijayajay17** [comment]
Hi @rymorale,

We are able to receive the response in the callback now, Thanks for all the help. 
I have one more question regarding the `TargetParameters`,

Initially in the 4x frameworks, we were able to set `Bool/Integer` or `String` as parameters dictionary values, but in the new Experiece Platform SDK, the parameters only takes values as Strings.

`public init(parameters: [String : String]? = nil, profileParameters: [String : String]? = nil, order: AEPTarget.TargetOrder? = nil, product: AEPTarget.TargetProduct? = nil)`

Is it that all the values we would be sending only in `String` values?

**Comment by rymorale** [comment]
Hi @vijayajay17, that is correct. All values should be sent as String: String key value pairs. Closing this issue as the original issue is resolved.
