### ISSUE TITLE
Analytics.getTrackingIdentifier{} 

### ISSUE THREAD

**Issue by vijayajay17** [Adobe-Marketing-Cloud/acp-sdks#581]
Hi Team,

We are migrating from 4x to new Exp.. platform SDK and facing an issue in getting the tracking identifier
Below is the code what we have tried

func setUpAEP() {
      MobileCore.setLogLevel(.debug)
      MobileCore.registerExtensions([Analytics.self, Identity.self, Target.self], {
           MobileCore.configureWith(appId: "App Id")
      })
      MobileCore.lifecycleStart(additionalContextData: nil)
      Analytics.getTrackingIdentifier {(trackingIdentifier, error) in
           ** trackingIdentifier is nil and error is callBackTimeout **
      }
}
//in the callback response, trackingIdentifier is nil and error is callBackTimeout. Please let us know is something is wrong/missing.

Thanks & regards

**Comment by sbenedicadb** [comment]
Hey @vijayajay17 - 

In an environment where you're using both `Analytics` and `Identity`, the value normally returned by `Analytics.getTrackingIdentifier` - `aid` - does not get generated.  Instead, `Analytics` will use the "Experience Cloud ID" (`ecid`) that is generated by the `Identity` extension for identifying visitors.  

If this doesn't help clear things up, maybe you can help me better understand your use case and expectations?  Thanks.

-steveb

**Comment by vijayajay17** [comment]
@sbenedicadb 
If my understanding is correct then, we will be using the "Experience Cloud ID" generated by `Identity` for `Analytics` also and there is no need to call `Analytics.getTrackingIdentifier` to get the `trackingIdentifier`.

**Comment by sbenedicadb** [comment]
Right, that's why I was asking what the use case was - I was trying to figure out if you had a need to retrieve  `trackingIdentifier`.  I agree with your assessment that it's not necessary.

-steveb
