### ISSUE TITLE
AEPMobileServices | non-modular header

### ISSUE THREAD

**Issue by vijayajay17** [Adobe-Marketing-Cloud/acp-sdks#582]
Hi Team,

We are migrating from 4x to new Exp.. platform SDK, when ever we are trying to import AEPMobileServices header we are getting the following error

"include of non-modular header inside framework module 'OurSDKModule'"

we are importing the header in the .h file
#import "AEPMobileServices.h"

Note: We have used the manual installation process of adding the xcframework into our project.

Thanks & Regards

**Comment by nporter-adbe** [comment]
Hi @vijayajay17 I believe this can be resolved by adding a modulemap to our XCFramework. I've done that here in my branch: https://github.com/nporter-adbe/acp-sdks/tree/aepmobileservices-map

Can you try out this build and let me know if it resolves your issue? If so we'll merge it into the main branch.

Thanks,
Nick

**Comment by nporter-adbe** [comment]
@vijayajay17 Could you provide a sample project which demonstrates this issue?

Thanks,
Nick

**Comment by vijayajay17** [comment]
Hi @nporter-adbe 

After adding the xcframework mentioned from the link https://github.com/nporter-adbe/acp-sdks/tree/aepmobileservices-map, it works fine.

**Comment by nporter-adbe** [comment]
@vijayajay17 Glad to hear. where did you download the AEPMobileServices you used originally? We'd like to get that one updated as well.
