### ISSUE TITLE
AEPTarget Parameter

### ISSUE THREAD

**Issue by NareshJain91** [Adobe-Marketing-Cloud/acp-sdks#583]
In SDK version 4.X we were using the below code for targetload
 
```
let myRequest = ADBMobile.targetCreateRequest(withName: “mBoxName”,
                                                          defaultContent: "",
                                                          parameters: [“BalanceIsLow”: true])  //true is BOOL value as Parameter previously was [String:Any]
            ADBMobile.targetLoad(myRequest) { result in
                print(result) //Result is always true
            }
```
 
As per the new API change

```
 let targetParams = TargetParameters.init(parameters: [“BalanceIsLow”: “true”], //true is String Value as parameter is [String:String]
profileParameters: nil, order: nil, product: nil)
        let targetRequest = TargetRequest.init(mboxName: “mBoxName”, defaultContent: “”, targetParameters: targetParams) { (result) in
            print(result) // Result is always false
        }
        Target.retrieveLocationContent([targetRequest])
```
 
Can you please suggest what we need to use if previously for a parameter we were sending Bool values?

**Comment by swarna04** [comment]
@NareshJain91 Thank you for reaching out. Yes, the 4.x API you are referring to is deprecated with v5 2.x and 3.x Target SDKs. You can find the complete changelog here - https://aep-sdks.gitbook.io/docs/api-change-log#adobe-target-extension-apis.

As you've correctly identified, we are more restrictive with Target parameter types in v5 SDK. Also, Target Product and Target Order are their own objects now for the same reason. This is to minimize errors during serializing when sending the requests to Target servers. You should still be able to set up audience rules in Target UI properly based on the passed custom mbox parameters. Please let us know more about your specific use case which you are unable to accomplish with the current set of APIs. And we will be happy to look further into this and to assist you with it. Thank you.

--
Swarna

**Comment by swarna04** [comment]
@NareshJain91 I'm resolving this issue in the absence of any further updates here. Please feel free to reach out in case of any other questions. Thank you.
