### ISSUE TITLE
library crashing on tvOS

### ISSUE THREAD

**Issue by baconst123** [Adobe-Marketing-Cloud/acp-sdks#595]
I am experiencing this crash when I implemented ACPCore to my application. I follow the documentation for initialization and it works for iOS but it doesn't for tvOS.

<img width="1054" alt="Screen Shot 2021-07-08 at 3 25 02 PM" src="https://user-images.githubusercontent.com/86008122/124972391-ac48b500-e000-11eb-994e-1bd8592315ee.png">

I have no much answer from the xcode log file too. But I attached here in case I am missing smth.
[xcode-log.txt](https://github.com/Adobe-Marketing-Cloud/acp-sdks/files/6786557/xcode-log.txt)

Any one have an idea what could be causing it to crash?

I am adding the libraries manually and I am using:
ACPCore - 2.9.4 (both iOS and tvOS)
ACPMedia - 2.3.1 (both iOS and tvOS)
ACPAnalytics - 2.5.0 (both iOS and tvOS)
ACPUserProfile - 2.2.0 (only iOS, didn't find it for tvOS)

XCode: 12.4
deployment target: tvOS 11.0 / iOS 11.0

**Comment by sbenedicadb** [comment]
Hey @baconst123 -

I think you might have an issue with your tvOS target.  The log indicates there is more than one definition for each of the SDK's classes, which usually means you're accidentally linking both the iOS *and* tvOS binaries.  Can you make sure you're only linking the tvOS binaries in your tvOS target?

Hope this helps.

-steveb

**Comment by baconst123** [comment]
Hi @sbenedicadb thank you for your answer, but this is not the case unfortunately. I have two libraries, a Core one and the main, both are linking correct as you can see in the prints:

<img width="390" alt="Screen Shot 2021-07-09 at 9 19 00 AM" src="https://user-images.githubusercontent.com/86008122/125076779-b4533400-e096-11eb-85e6-051fcac536ab.png">
<img width="419" alt="Screen Shot 2021-07-09 at 9 19 37 AM" src="https://user-images.githubusercontent.com/86008122/125076847-caf98b00-e096-11eb-9f13-40c871ceb2c0.png">
<img width="445" alt="Screen Shot 2021-07-09 at 9 20 51 AM" src="https://user-images.githubusercontent.com/86008122/125076983-f67c7580-e096-11eb-9c79-07e86155393b.png">

**Comment by sbenedicadb** [comment]
Hey @baconst123 - 

Are each of these targets being built and failing separately, or are they both added as dependencies to another target?

We've tried to reproduce the issue internally and haven't been able to.

Are you able to provide us a project that reproduces the issue?  Thanks.

-steveb

**Comment by baconst123** [comment]
Hi @sbenedicadb  

I cannot give you access to this project since it is a private repo from the company.

But let me explain it better. There are three different libraries: Core (first print), Features (didn't have to link Adobe) and the Main (second print) where I have the Core and Features imported as dependencies and I handle the View Controllers.

I had to link Adobe libraries with Core, where I handle API calls, Data Parsing, Deeplinking, and Adobe Manager. And I had to link to the Main where I call the Video tracking in the View Controllers. The crash happens after the build, so I am able to initialize Adobe in AppDelegate and right after that it crashes. 

I hope I made it clearer, and let me know if that helps.

**Comment by sbenedicadb** [comment]
Hey @baconst123 -

Sorry for the miscommunication - I didn't specify that I was looking for a standalone project to reproduce the issue, not your company's source code 😄 .   

Trying to make sure I understand your setup - it sounds like you're linking the SDK twice (once from your Core and once from your Main).  If both of these targets are linking the SDK, then there are two definitions and the app doesn't know which one to use:

    Class ACPExtension is implemented in both /Users/bruno/Library/Developer/Xcode/DerivedData/CN-Video-bcspewjkwckbuhhggebxebeviwtj/Build/Products/CN tvOS Debug-appletvsimulator/CNCore.framework/CNCore (0x10b8a6370) 
    and /Users/bruno/Library/Developer/CoreSimulator/Devices/27FD23E0-692D-4D59-9954-081921FBE038/data/Containers/Bundle/Application/0E0820EB-C5E2-49C5-BB5A-233FA9F2ECA2/CN-tvOS.app/CN-tvOS (0x10a50eae8). 
    One of the two will be used. Which one is undefined.

The SDK need to be linked only once.  If the Core library links it, and the Main app depends on Core, then you should be able to get access to the SDK transitively.  In this case, removing the dependency on the SDK from Main should fix the issue.

Let me know.  Thanks.

-steveb

**Comment by baconst123** [comment]
Hey @spoorthipujariadobe,

It was fixed by removing all the libraries from Adobe and re-adding them in my Core library and them inheriting it to the other libraries. I am sorry I forgot to close the issue.
