### ISSUE TITLE
Tracking analytics while app is in background

### ISSUE THREAD

**Issue by zzt4** [Adobe-Marketing-Cloud/acp-sdks#596]
Is it possible to continue tracking analytics in the background? We typically do this in our app but with leveraging the new SDKs, it looks like this might not be supported. In `applicationDidEnterBackground()` the documentation  says to call `ACPCore.lifecyclePause()`. Does this prevent analytics from being sent in the background?

**Comment by addb** [comment]
That is for tracking the app state (lifecycle metrics). Analytics hits will be sent with corresponding trackState or trackAction API call even in the background.  

-Arjun

**Comment by zzt4** [comment]
Thank you!
