### ISSUE TITLE
iOS - AEPAssurance - Cannot start session due to WebPageProxy didFailProvisionalLoadForFrame  error

### ISSUE THREAD

**Issue by chongsawad-nice** [Adobe-Marketing-Cloud/acp-sdks#622]
### Project

Xcode 13.0
iOS Target: 15.0

Podfile.lock
```
PODS:
  - ACPAnalytics (2.5.1):
    - ACPAnalytics/xcframeworks (= 2.5.1)
    - ACPCore (>= 2.9.0)
  - ACPAnalytics/xcframeworks (2.5.1):
    - ACPCore (>= 2.9.0)
  - ACPCore (2.9.4):
    - ACPCore/main (= 2.9.4)
  - ACPCore/main (2.9.4)
  - ACPUserProfile (2.2.0):
    - ACPCore (>= 2.9.0)
    - ACPUserProfile/xcframeworks (= 2.2.0)
  - ACPUserProfile/xcframeworks (2.2.0):
    - ACPCore (>= 2.9.0)
  - AEPAssurance (1.1.3):
    - ACPCore (>= 2.9.0)
    - AEPAssurance/xcframeworks (= 1.1.3)
  - AEPAssurance/xcframeworks (1.1.3):
    - ACPCore (>= 2.9.0)
```

### Problem
After launched the app with configured session, it could not connect and got error log below

`[pageProxyID=33, webPageID=34, PID=15062] WebPageProxy::didFailProvisionalLoadForFrame: frameID=3, domain=NSURLErrorDomain, code=-1002`

<img width="1788" alt="Screen Shot 2564-10-26 at 21 55 32" src="https://user-images.githubusercontent.com/69631049/138910201-5eba6697-f344-432b-9567-df13584ef628.png">

Hit "Connect" button produces the same error as shown.

**Comment by PravinPK** [comment]
Hi @chongsawad-nice,

By any chance, does your app also include Dynatrace Replay SDK along with Assurance? 
We have seen similar issues where the webView's local navigation is blocked by Dynatrace SDK. Let us know.


Pravin Prakash Kumar
Computer Scientist
Adobe

**Comment by chongsawad-nice** [comment]
Hi @PravinPK Thanks for response. 

By any chance, does your app also include Dynatrace Replay SDK along with Assurance?
**>> Yes we have.** 

```
 - Dynatrace/SessionReplay (8.227.1.1019):
    - Dynatrace/SessionReplayXCFramework
  - Dynatrace/SessionReplayXCFramework (8.227.1.1019):
    - Dynatrace/xcframework
  - Dynatrace/xcframework (8.227.1.1019)
```

Let me know if you need more info.

Thanks,
Chongsawad

**Comment by PravinPK** [comment]
@chongsawad-nice We found a workaround working with the Dynatrace team.

The workaround was to Dynatrace agent manually

Setting DTXAutoStart to false into the info.plist file.
Adding Dynatrace.startWithInfoPlistSettings() along with the rest of the Dynatrace SDK config to be the last things to load in AppDelegate
