### ISSUE TITLE
Veracode Scan reported Unchecked Return Value (CWE ID 252) issue

### ISSUE THREAD

**Issue by dimas-isharmaya** [Adobe-Marketing-Cloud/acp-sdks#623]
We have AEP SDK/ACPPlaces v	1.0 integrated in our iOS mobile app that is already available in App Store. As part of security implementation review, the app is being scanned using Veracode.
Issue is found on ACPPlacesMonitorInternal.m where Veracode reported Server Error Handling Issues > Unchecked Return Value (CWE ID 252). Report mentioned the issue is "Ignoring a method's return value can cause the program to overlook unexpected states and conditions."

The issue is reported on the following line of code from ACPPlacesMonitorInternal.m: 
'auth = [CLLocationManager authorizationStatus]'
```
- (void) startMonitoring {
    CLAuthorizationStatus auth;
    if (@available(iOS 14.0, *)) {
        auth = _locationManager.authorizationStatus;
    } else {
        auth = [CLLocationManager authorizationStatus];
    }
```

.../ACPPlacesMonitorInternal.m 444 
.../ACPPlacesMonitorInternal.m 485 
.../ACPPlacesMonitorInternal.m 589

**Comment by sbenedicadb** [comment]
Hey @dimas-isharmaya -

This is likely a false positive, as the highlighted code runs entirely on the client and has nothing to do with handling any errors returned from a server.  

Can you provide more information, or shall we just close this issue?  Thanks.

-steveb

**Comment by addb** [comment]
@dimas-isharmaya If you still need help with this issue, please open a ticket with our [Client Support Team](https://experienceleague.adobe.com/?support-solution=General#support)
