### ISSUE TITLE
Support for Swift Package Panager

### ISSUE THREAD

**Issue by yharshal** [Adobe-Marketing-Cloud/acp-sdks#626]
As we know, a new dependency manager is available, Adobe must provide support for the swift package manager for all the libraries they have.

**Comment by emdobrin** [comment]
@yharshal thanks for you feedback and yes!!! we do have SPM support for our latest version of the Adobe Experience Platform Mobile SDKs. 
Here is the AEPCore extension https://github.com/adobe/aepsdk-core-ios . 
Check out the full list here https://aep-sdks.gitbook.io/docs/resources/upgrading-to-aep/current-sdk-versions#ios-swift

- Emilia

**Comment by yharshal** [comment]
Thanks for the update @emdobrin.
Will check the latest SDK.

**Comment by emdobrin** [comment]
Hi @mt-hodaka, the changes should be minimal for most of the APIs, once you upgraded the libraries to AEP you can follow the [Migration API reference docs](https://aep-sdks.gitbook.io/docs/resources/migrate-to-swift#update-api-usage-and-references-for-each-extension) for the extensions you use.

**Comment by mt-hodaka** [comment]
@emdobrin Thanks for your reply.
I'll try it.
