### ISSUE TITLE
Android Connectivity Issue With New Analytics SDK

### ISSUE THREAD

**Issue by VishalThareja** [Adobe-Marketing-Cloud/acp-sdks#627]
Getting the following error while connecting to the latest analytics SDK.

###  W/AdobeExperienceSDK: HttpConnectionHandler - Connection failure (Unable to resolve host "assets.adobedtm.com": No address associated with hostname)
 W/AdobeExperienceSDK: HttpConnection - Could not get response code. (java.net.UnknownHostException: Unable to resolve host "assets.adobedtm.com": No address associated with hostname)
 W/AdobeExperienceSDK: HttpConnection - Could not get response code. (java.net.UnknownHostException: Unable to resolve host "assets.adobedtm.com": No address associated with hostname)
 W/AdobeExperienceSDK: HttpConnection - Could not get response code. (java.net.UnknownHostException: Unable to resolve host "assets.adobedtm.com": No address associated with hostname)
 W/AdobeExperienceSDK: HttpConnection - Could not get response code. (java.net.UnknownHostException: Unable to resolve host "assets.adobedtm.com": No address associated with hostname)
 W/AdobeExperienceSDK: HttpConnection - Could not get response code. (java.net.UnknownHostException: Unable to resolve host "assets.adobedtm.com": No address associated with hostname)
W/AdobeExperienceSDK: HttpConnection - Could not get the response message. (java.net.UnknownHostException: Unable to resolve host "assets.adobedtm.com": No address associated with hostname)
W/AdobeExperienceSDK: RemoteDownloader - File could not be downloaded from URL () Response: (-1) Message: (null)
 W/AdobeExperienceSDK: HttpConnection - Could not get the input stream. (java.net.UnknownHostException: Unable to resolve host "assets.adobedtm.com": No address associated with hostname)
 D/AdobeExperienceSDK: ConfigurationExtension - Problem while downloading config.
 D/AdobeExperienceSDK: CacheManager - Cached Files - Directory is empty 
 D/AdobeExperienceSDK: ConfigurationExtension - Either there was no cached config, or there was a problem loading the cached  W/AdobeExperienceSDK: ConfigurationExtension - Unable to fetch config. Rolling back to the previous configuration.

We are using following dependencies:

    **implementation 'com.adobe.marketing.mobile:edgeidentity:1.+'
    implementation 'com.adobe.marketing.mobile:analytics:1.+'
    implementation 'com.adobe.marketing.mobile:assurance:1.+'
    implementation 'com.adobe.marketing.mobile:userprofile:1.+'
    implementation 'com.adobe.marketing.mobile:sdk-core:1.+'**

**Comment by shtomar-adb** [comment]
Hi @VishalThareja,

One reason for this issue could be that the network connectionIs is blocked by a Proxy or a Firewall. Please verify that this is not the case.

**Comment by VishalThareja** [comment]
Hi @shtomar-adb,

I tried the same on my own internet network, but that doesn't have any Proxy or Firewall restrictions. 
Also yes I tried it on another system, their connections request is blocked by Proxy/Firewall. Need to check for this URL.

**But for another system, it doesn't have any restrictions. Could you please suggest more in deeper?**

**Comment by shtomar-adb** [comment]
@VishalThareja 

The problem could also be the internet connectivity issues at the time app made this network request. 
Could you please provide verbose debug logs to look more into it.

**Comment by ahmyr** [comment]
@VishalThareja, if you put "assets.adobedtm.com" in a browser window on your device, does it find it? Or, do you get an error that the address cannot be found?

**Comment by VishalThareja** [comment]
@ahmyr-  for the browser I am being able to open this URL, but in the device or emulator, I am not being able to connect.

One Quick Solution I did is using Certificates to be added to my app, but want to know is it recommended as per your documentation?

@shtomar-adb - Verbose logs are the same for which I raised tickets, it shows SSL Handshake exception.

**Comment by shtomar-adb** [comment]
@VishalThareja You should not need to add any certificate for connecting to the URL. Can you elaborate more which certificate you added to the app for making it work. 
Is you Android phone/emulator connected to any proxy that needs you to add a certificate explicitly?

**Comment by addb** [comment]
Hey @VishalThareja were you able to get this resolved?

**Comment by addb** [comment]
@VishalThareja If you still need help with this issue, please feel free to open a ticket with our [Client Support Team](https://experienceleague.adobe.com/?support-solution=General#support)

**Comment by VishalThareja** [comment]
> Hey @VishalThareja were you able to get this resolved?

Yes, it is being fixed
