### ISSUE TITLE
Adobe ACPCore sdk

### ISSUE THREAD

**Issue by raja-datascientist** [Adobe-Marketing-Cloud/acp-sdks#628]
I am trying to use Adobe objective sdk acpcore 2.9.4 in one of my project. Please let me know is this compactible with iOS 15?

**Comment by addb** [comment]
@raja-datascientist It is compatible with iOS 15. Are you seeing any issues?

**Comment by raja-datascientist** [comment]
No issues . I wanted to start using it in one of my project.
