### ISSUE TITLE
The library crash on iOS

### ISSUE THREAD

**Issue by DevWithLove** [Adobe-Marketing-Cloud/acp-sdks#631]
Hey, 

We are seeing crashes on iOS SDK,  please see the following details :

Versions we are using: 
        .package(name: "AEPAnalytics", url: "https://github.com/adobe/aepsdk-analytics-ios.git", .exact("3.0.1")),
        .package(name: "AEPRulesEngine", url: "https://github.com/adobe/aepsdk-rulesengine-ios.git", .exact("1.0.1")),
        .package(name: "AEPCore", url: "https://github.com/adobe/aepsdk-core-ios.git", .exact("3.2.3")),
        .package(name: "AEPTarget", url: "https://github.com/adobe/aepsdk-target-ios.git", .exact("3.1.0")),
        .package(name: "AEPUserProfile", url: "https://github.com/adobe/aepsdk-userprofile-ios.git", .exact("3.0.1")),
        .package(name: "AEPAudience", url: "https://github.com/adobe/aepsdk-audience-ios.git", .exact("3.0.2")),

Crash logs:

Crashed: com.adobe.eventHub.queue
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00009b11cce74e80

0  libobjc.A.dylib                0x15e0 objc_msgSend + 32
1  libobjc.A.dylib                0x1b010 objc_object::sidetable_release(bool, bool) + 228
### **2  Analytics                      0x38498 closure #1 in EventHub.getSharedState(extensionName:event:barrier:sharedStateType:) + 242 (EventHub.swift:242)**
3  Analytics                      0x3dc90 partial apply for thunk for @callee_guaranteed () -> (@owned SharedStateResult?, @error @owned Error) + 4340391056 (<compiler-generated>:4340391056)
4  Analytics                      0x3e1a0 thunk for @callee_guaranteed () -> (@owned SharedStateResult?, @error @owned Error)partial apply + 4340392352
5  libswiftDispatch.dylib         0x1938 partial apply for thunk for @callee_guaranteed () -> (@out A, @error @owned Error) + 28
6  libswiftDispatch.dylib         0x8c18 thunk for @callee_guaranteed () -> (@out A, @error @owned Error)partial apply + 16
7  libswiftDispatch.dylib         0x2c70 closure #1 in closure #1 in OS_dispatch_queue._syncHelper<A>(fn:execute:rescue:) + 188
8  libswiftDispatch.dylib         0x2d5c partial apply for thunk for @callee_guaranteed () -> () + 28
9  libswiftDispatch.dylib         0x2680 thunk for @escaping @callee_guaranteed () -> () + 28
10 libdispatch.dylib              0x4660 _dispatch_client_callout + 20
11 libdispatch.dylib              0x13ce4 _dispatch_sync_invoke_and_complete_recurse + 64
12 libdispatch.dylib              0x13760 _dispatch_sync_f_slow + 172
13 libswiftDispatch.dylib         0x1ffc implicit closure #2 in implicit closure #1 in OS_dispatch_queue.sync<A>(execute:) + 180
14 libswiftDispatch.dylib         0x1074 partial apply for implicit closure #2 in implicit closure #1 in OS_dispatch_queue.sync<A>(execute:) + 56
15 libswiftDispatch.dylib         0x1d8c OS_dispatch_queue._syncHelper<A>(fn:execute:rescue:) + 396
16 libswiftDispatch.dylib         0x1124 OS_dispatch_queue.sync<A>(execute:) + 168
17 Analytics                      0x3db58 @objc ExtensionContainer.getSharedState(extensionName:event:barrier:) + 4340390744
18 Analytics                      0x3cbe0 Extension.getSharedState(extensionName:event:) + 115 (Extension.swift:115)
19 Analytics                      0x10393c Identity.readyForEvent(_:) + 67 (Identity.swift:67)
20 Analytics                      0x103aa4 @objc Identity.readyForEvent(_:) + 4341201572 (<compiler-generated>:4341201572)
21 Analytics                      0x3ceac ExtensionContainer.eventProcessor(_:) + 147 (ExtensionContainer.swift:147)
22 Analytics                      0x3e0f8 partial apply for thunk for @escaping @callee_guaranteed (@guaranteed Event) -> (@unowned Bool) + 4340392184 (<compiler-generated>:4340392184)
23 Analytics                      0x7e744 OperationOrderer.drain() + 128 (OperationOrderer.swift:128)
24 Analytics                      0x5df90 thunk for @escaping @callee_guaranteed () -> () + 4340522896 (<compiler-generated>:4340522896)
25 libdispatch.dylib              0x2914 _dispatch_call_block_and_release + 32
26 libdispatch.dylib              0x4660 _dispatch_client_callout + 20
27 libdispatch.dylib              0xbde4 _dispatch_lane_serial_drain + 672
28 libdispatch.dylib              0xc958 _dispatch_lane_invoke + 392
29 libdispatch.dylib              0x171a8 _dispatch_workloop_worker_thread + 656
30 libsystem_pthread.dylib        0x10f4 _pthread_wqthread + 288
31 libsystem_pthread.dylib        0xe94 start_wqthread + 8

**Comment by addb** [comment]
Hey @DevWithLove,

Thanks for letting us know, we are looking into this issue. Do we have steps to reproduce this crash?

**Comment by praveek** [comment]
@DevWithLove The crash looks similar to the one we fixed in [AEPCore v3.2.4](https://github.com/adobe/aepsdk-core-ios/releases/tag/3.2.4).

**Comment by DevWithLove** [comment]
Thanks @praveek, we will upgraded it to the latest version.

**Comment by addb** [comment]
@DevWithLove Did upgrading to the latest version solve the issue?

**Comment by addb** [comment]
@DevWithLove If you still need help with this issue, please feel free to open a ticket with our [Client Support Team](https://experienceleague.adobe.com/?support-solution=General#support)
