### ISSUE TITLE
1.2.10 Broken the build

### ISSUE THREAD

**Issue by nksaroj** [Adobe-Marketing-Cloud/acp-sdks#641]
> Could not find analytics-1.2.10.jar (com.adobe.marketing.mobile:analytics:1.2.10).
     Searched in the following locations:
         https://plugins.gradle.org/m2/com/adobe/marketing/mobile/analytics/1.2.10/analytics-1.2.10.jar

**Comment by emdobrin** [comment]
Hi @nksaroj, 

The latest versions of Adobe Experience Platform Mobile SDKs for Android are published to MavenCentral as JCenter repository is now read-only, for more details see [JCenter service update](https://developer.android.com/studio/build/jcenter-migration). 
You can find the latest version here: https://search.maven.org/artifact/com.adobe.marketing.mobile/analytics/1.2.10/aar and you can download it through Gradle by including mavenCentral() to the repositories list (build.gradle file):

```
repositories {
    ...
    mavenCentral()
}
```

Let us know if you are able to download it this way.

Thank you,
Emilia Dobrin

**Comment by nksaroj** [comment]
I am facing the same issues.

**Comment by emdobrin** [comment]
@nksaroj seems like both the links you shared point to JCenter repository. Have you tried referencing the MavenCentral repository instead?
Alternatively, you can also find the library here: https://github.com/Adobe-Marketing-Cloud/acp-sdks/blob/master/android/analytics-1.2.10.aar

**Comment by addb** [comment]
@nksaroj Were you able to resolve this issue?

**Comment by nksaroj** [comment]
No, I am facing the same issue still.So, have gone back to 1.2.9 as it's working

**Comment by addb** [comment]
Here is the **Maven** artifact for our analytics library: 
https://search.maven.org/artifact/com.adobe.marketing.mobile/analytics
https://search.maven.org/artifact/com.adobe.marketing.mobile/analytics/1.2.10/aar

Can you make sure you are adding `mavenCentral()` in your repositories as suggested by @emdobrin before?

**Comment by addb** [comment]
@nksaroj If you still need help with this issue, please feel free to open a ticket with our [Client Support Team](https://experienceleague.adobe.com/?support-solution=General#support)
