### ISSUE TITLE
[Android] Crash: Integer cannot be stored accurately in a Variant

### ISSUE THREAD

**Issue by SemihGk** [Adobe-Marketing-Cloud/acp-sdks#658]
Crash in Adobe SDK media:2.1.2 and core: 1.10.1

```

com.adob...gVariant | LongVariant.java line 38 in com.adobe.marketing.mobile.LongVariant.<init>()
-- | --
com.adob...gVariant | LongVariant.java line 33 in com.adobe.marketing.mobile.LongVariant.from()
com.adob....Variant | Variant.java line 125 in com.adobe.marketing.mobile.Variant.fromLong()
com.adob...onHelper | MediaCollectionHelper.java line 232 in com.adobe.marketing.mobile.MediaCollectionHelper.extractQoEData()
com.adob...enerator | MediaCollectionHitGenerator.java line 208 in com.adobe.marketing.mobile.MediaCollectionHitGenerator.processBitrateChange()
com.adob...acker$40 | MediaCollectionTracker.java line 724 in com.adobe.marketing.mobile.MediaCollectionTracker$40.call()
com.adob...ediaRule | MediaRule.java line 147 in com.adobe.marketing.mobile.MediaRule.runActions()
com.adob...leEngine | MediaRuleEngine.java line 81 in com.adobe.marketing.mobile.MediaRuleEngine.processRule()
com.adob...nTracker | MediaCollectionTracker.java line 156 in com.adobe.marketing.mobile.MediaCollectionTracker.processRule()
com.adob...nTracker | MediaCollectionTracker.java line 1157 in com.adobe.marketing.mobile.MediaCollectionTracker.prerollDeferRule()
com.adob...nTracker | MediaCollectionTracker.java line 148 in com.adobe.marketing.mobile.MediaCollectionTracker.track()
com.adob...xtension | MediaExtension.java line 213 in com.adobe.marketing.mobile.MediaExtension.trackMedia()
com.adob...xtension | MediaExtension.java line 162 in com.adobe.marketing.mobile.MediaExtension.handleMediaTrackEvent()
com.adob...kMedia$1 | MediaListenerTrackMedia.java line 41 in com.adobe.marketing.mobile.MediaListenerTrackMedia$1.run()
java.uti...Executor | ThreadPoolExecutor.java line 1167 in java.util.concurrent.ThreadPoolExecutor.runWorker()
java.uti...r$Worker | ThreadPoolExecutor.java line 641 in java.util.concurrent.ThreadPoolExecutor$Worker.run()
java.lang.Thread | Thread.java line 764 in java.lang.Thread.run()

```

After checking the class where it throws the exception at this function => 

```
    private LongVariant(long value) {
        if (value <= 9007199254740991L && value >= -9007199254740991L) {
            this.value = value;
        } else {
            throw new IllegalArgumentException("Integer cannot be stored accurately in a Variant");
        }
    }
```

In terms of how we create QoEObject, here is the code block =>

```
        Map<String, Object> qoeObject = Media.createQoEObject(Double.valueOf(bitrate).longValue(), startupTime, fps, Double.valueOf(droppedFrames).longValue());
        tracker.updateQoEObject(qoeObject);
        tracker.trackEvent(Media.Event.BitrateChange, null, null);
```
As you can see, ```Media.createQoEObject``` takes long, double, double, long params. Although I cannot reproduce the issue, I suspect a live content startTime exceeds the Integer max value. So, can we get clarification on this part? Should we add a check for each param not to exceed Integer.MAX and Integer.Min values even though params are sent long and double? It totally misleads us.

**Comment by addb** [comment]
@SemihGk We are investigating this issue and will make an appropriate fix to handle this issue internally and not crash. Till that time you could verify that even in error you set it as 0.0 and not MAX_VALUES. Ideally the time should not exceed the limit, so we are suspecting there is some error workflow in which app's player code is passing Max values.

**Comment by SemihGk** [comment]
Thanks for your response @addb . I was planning to ignore calling` tracker.updateQoEObject` and` tracker.trackEvent` in case of the crash condition. So, would you still recommend to send 0 instead of calling the APIs?

**Comment by addb** [comment]
If you think it is not necessary to update QoE for that state it should be fine not calling it. if there are other parameters which needs to be updated like bitrate/ fps then call it with 0.0

**Comment by SemihGk** [comment]
Sure. I initially thought sending 0 may introduce other issues in HE as it is not the correct value at the time. If it is safer than not invoking, I would do it. Thanks for the advice.
