### ISSUE TITLE
Failed to parse the target.clientCode from config

### ISSUE THREAD

**Issue by Angad-Tiwari** [Adobe-Marketing-Cloud/acp-sdks#663]
I am using latest adobe target sdk & code 

`implementation 'com.adobe.marketing.mobile:sdk-core:1.11.0'`
`implementation 'com.adobe.marketing.mobile:target:1.2.8'`
  
Target API won't able to parse the clientCode from the ADBMobileConfig.json   
<img width="599" alt="Screenshot 2022-06-27 at 5 31 55 PM" src="https://user-images.githubusercontent.com/87816236/175939128-5a7efa94-8357-4276-8733-106bee8cd785.png">

TargetExtension.class > prepareForTargetRequest() > String newClientCode = configData.optString("target.clientCode", ""); 

`configData.optString("target.clientCode", "")` throws VariantException
<img width="846" alt="Screenshot 2022-06-27 at 5 35 32 PM" src="https://user-images.githubusercontent.com/87816236/175938690-72f8e9c0-571e-413f-9498-fb3c0900e81c.png">

**Comment by yangyansong-adbe** [comment]
@Angad-Tiwari we're trying to reproduce this issue locally to find the root cause. We will share more information later.

**Comment by yangyansong-adbe** [comment]
@Angad-Tiwari Just verified that your configuration file is not supported in V5 SDK (it looks like the configuration file for V4 SDK). The following is an example of the configuration file for V5 SDK:
```
{
  "rules.url": "xxxxxxx",
  "experienceCloud.org": "xxxx@AdobeOrg",
  "target.clientCode": "xxxxx",
  "lifecycle.sessionTimeout": 300,
  "target.timeout": 5,
  "target.propertyToken": "",
  "global.privacy": "optedin",
  "target.environmentId": 0,
  "target.server": "",
  "property.id": "xxxx",
  "build.environment": "dev"
}
```
Here is the documentation of [how to use a bundled file configuration](https://aep-sdks.gitbook.io/docs/foundation-extensions/mobile-core/configuration#using-a-bundled-file-configuration) in V5 SDKs. Let me know if you have any other questions.

**Comment by Angad-Tiwari** [comment]
thanks @yangyansong-adbe for looking into that.

Although, I was unable to download the configuration file for the latest SDK. Followed the link you shared, and added the env-id with the url to download it, but received 'not found' error. (plz ref. screenshot)
<img width="575" alt="Screenshot 2022-06-28 at 3 50 22 PM" src="https://user-images.githubusercontent.com/87816236/176156330-68610fbb-3744-402f-b447-19250ca7b6db.png">

Tried adding the missing configuration using `MobileCore.updateConfiguration()`, and the target.clientCode issue resolved. 
<img width="441" alt="Screenshot 2022-06-28 at 3 53 12 PM" src="https://user-images.githubusercontent.com/87816236/176156487-932811ea-016a-4f46-9b1c-772c267ee478.png">

Now, the receiving the error 
`{
  "status": 400,
  "message": "Errors: field - [execute.mboxes] - global mbox is not allowed in mboxes.;"
}`
from target while hitting the TargetRequest
<img width="1345" alt="Screenshot 2022-06-28 at 2 53 41 PM" src="https://user-images.githubusercontent.com/87816236/176156951-6b38fe57-1256-4cf8-8852-3b7c648380b7.png">
<img width="315" alt="Screenshot 2022-06-28 at 2 54 05 PM" src="https://user-images.githubusercontent.com/87816236/176157027-7d65c98c-dd6a-4841-a2f9-69e078b5d464.png">

This global mbox name is working on iOS and they are using the latest SDK i.e. AEP

Could you help me here !!

Thanks in Advance.

**Comment by yangyansong-adbe** [comment]
@Angad-Tiwari , did you get the env-id from the Data Collection UI as below? 
<img width="1194" alt="Screen Shot 2022-06-28 at 2 52 50 PM" src="https://user-images.githubusercontent.com/47394585/176286100-a2212915-7184-4128-b185-fcb15d4f4c1a.png">
The url should look like this -> https://assets.adobedtm.com/3xxxxxxxxxx/dxxxxxxxxx/launch-2xxxxxxxx-development.json

**Comment by yangyansong-adbe** [comment]
@swarna04  I'm not very similar with Target configurations. Can you help answer the above `target.clientCode` question?

Thanks.

**Comment by archanajain** [comment]
What is the specific question about Target 'client code' config? The V5-Target SDK reads configuration from the values configured in Launch/Data-collection UI. The 'client code' field is auto-populated in the extension configuration UI. If Adobe Launch is used to do the configuration, there should not be any parse error.

**Comment by Angad-Tiwari** [comment]
@archanajain 
I'm getting the parse error while fetching the target.clientCode param, because the v4 configuration file is not compatible with the latest SDK, for this need to download the latest configuration from Data Collection UI, but somehow still not able to download the file. Although, I used the updateConfiguration() method to dynamically set the configuration params and it's work, but still the latest SDK won't work as expected and I'm not able to fetch the JSON offer (response) from the A/B Test Activity.

**Comment by Angad-Tiwari** [comment]
thanks @yangyansong-adbe 
I was able to by-pass the target.clientCode issue, by setting the configuration dynamically using updateConfiguration() method. Although, not able to fetch the latest configuration (it throws page not found error) using the url https://assets.adobedtm.com/{env-id}.json. 

Also, not able to get the response (JSON offer) from target for A/B Test using the latest Android SDK, but somehow it's working using v4 SDK.

Whereas, the clientCode issue is resolved, so closing this ticket. Thanks once again for all the support.
