### ISSUE TITLE
The link to the "newer version" is broken (AEP Mobile SDKs 3.x)

### ISSUE THREAD

**Issue by msmtamburro** [Adobe-Marketing-Cloud/acp-sdks#677]
The link in the readme 404's:
https://developer.adobe.com/client-sdks/documentation/resources/upgrading-to-aep/current-sdk-versions#ios-swift

Where are the 3.x SDKs hosted?

**Comment by msmtamburro** [comment]
Looks like they are here: https://github.com/adobe/aepsdk-core-ios

**Comment by emdobrin** [comment]
@msmtamburro thanks for letting us know, we updated the links. Indeed, the 3.x SDKs are open source, you can find the full list here  https://developer.adobe.com/client-sdks/documentation/current-sdk-versions/#ios--swift
