### ISSUE TITLE
Crash in latest iOS versions of ACPCore / ACPAnalytics

### ISSUE THREAD

**Issue by FL-RicPerrott** [Adobe-Marketing-Cloud/acp-sdks#684]
We are experiencing quite a few crash reports for these modules. I will attach the full stack crash report, however, the relevant crashing thread is always the same:

`Thread
0  libsystem_kernel.dylib         0x167c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  libc++.1.dylib                 0xcb68 std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 100
3  Analytics                      0xb56a0 std::__1::cv_status std::__1::condition_variable::wait_until<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&) + 200
4  Analytics                      0xcd128 std::__1::__function::__func<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2, std::__1::allocator<AdobeMarketingMobile::WorkerMain(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&, std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorWorkerData> const&)::$_2>, void ()>::operator()() + 1392
5  Analytics                      0xc977c AdobeMarketingMobile::TryCatch(std::__1::function<void ()> const&, std::__1::function<void (AdobeMarketingMobile::SdkError&)> const&) + 44
6  Analytics                      0xc96cc AdobeMarketingMobile::TrySwallow(std::__1::function<void ()> const&) + 60
7  Analytics                      0xcca0c void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, AdobeMarketingMobile::CreateWorkerThread(std::__1::shared_ptr<AdobeMarketingMobile::TaskExecutorData> const&)::$_1> >(void*) + 124
8  libsystem_pthread.dylib        0x16cc _pthread_start + 148
9  libsystem_pthread.dylib        0xba4 thread_start + 8`

Our Podfile is configured as such:

`PODS:
  - ACPAnalytics (2.5.4):
    - ACPAnalytics/xcframeworks (= 2.5.4)
    - ACPCore (>= 2.9.6)
  - ACPAnalytics/xcframeworks (2.5.4):
    - ACPCore (>= 2.9.6)
  - ACPCore (2.9.6):
    - ACPCore/main (= 2.9.6)
  - ACPCore/main (2.9.6)
  - ACPTarget (2.2.0):
    - ACPCore (>= 2.9.0)
    - ACPTarget/xcframeworks (= 2.2.0)
  - ACPTarget/xcframeworks (2.2.0):
    - ACPCore (>= 2.9.0)`

We are seeing these crashes with all OS versions on all device types. We would like to understand why this is happening.

[crash_issue_25fa778247695dc074a87a8265cbcaa2_crash_session_d9229cceee0b43f69e4e1df3cf53ff6d_DNE_0_v2_stacktrace.txt](https://github.com/Adobe-Marketing-Cloud/acp-sdks/files/10805250/crash_issue_25fa778247695dc074a87a8265cbcaa2_crash_session_d9229cceee0b43f69e4e1df3cf53ff6d_DNE_0_v2_stacktrace.txt)

**Comment by praveek** [comment]
@FL-RicPerrott Thanks for the report. We will investigate further and update the issue with our findings.

**Comment by FL-RicPerrott** [comment]
Hello, any progress on this? We are literally seeing thousands of these crashes every week.

Thank you.

**Comment by praveek** [comment]
Thank you for your patience. We ran some tests and could not reproduce the problem. The crash report was also not very helpful in narrowing down the underlying cause, as all SDK threads in the attached file are currently in a waiting state. 

We will continue investigating the issue and, in the meantime, I would also recommend updating to our newer version of the iOS SDK written in Swift. Please refer to the [migration guide](https://developer.adobe.com/client-sdks/previous-versions/documentation/migrate-to-swift/) and [latest SDK versions](https://developer.adobe.com/client-sdks/documentation/current-sdk-versions/#ios).

**Comment by emdobrin** [comment]
Hi @FL-RicPerrott were you able to update to the latest SDK version and resolve this issue?

**Comment by praveek** [comment]
@FL-RicPerrott Starting Aug 31, 2023, Adobe will be deprecating ACP iOS SDKs and wrappers. Refer [here](https://developer.adobe.com/client-sdks/documentation/resources/acp-end-of-support) for more information.

We encourage you to migrate to the latest Adobe Experience Platform versions of the Mobile SDK to ensure continued compatibility and support. Documentation for the latest versions of the Adobe Experience Platform Mobile SDKs can be found [here](https://developer.adobe.com/client-sdks/documentation/current-sdk-versions/ and the iOS migration guide can be found [here](https://developer.adobe.com/client-sdks/previous-versions/documentation/migrate-to-swift/).
