### ISSUE TITLE
Adobe expected target Parameters for Adobe IOS Sdk Adobe Target call.,

### ISSUE THREAD

**Issue by shravanteegala** [Adobe-Marketing-Cloud/acp-sdks#690]
Team,
Which data adobe expected from targetParameters from IOS  mboxParameters ,TargetPrefetch, TargetParameters,  these parameters in a Target request.
based on Adobe documentation  here they give sample hardcoded(static data) values like below code .
so here which data(dynamic) or which kind of data  adobe expected. can you please help.

NSDictionary *mboxParameters = @{@"status":@"Platinum"};
NSDictionary *profileParameters = @{@"gender":@"female"};
AEPTargetProduct *product =[[AEPTargetProduct alloc] initWithProductId:@"pId1" categoryId:@"cId1"];
AEPTargetOrder *order = [[AEPTargetOrder alloc] initWithId:@"id1" total:1.0 purchasedProductIds:@[@"ppId1"]];
AEPTargetParameters * targetParams = [[AEPTargetParameters alloc] initWithParameters:mboxParameters profileParameters:profileParameters order:order product:product];

**Comment by rymorale** [comment]
Hi @shravanteegala, the data entered in the target parameters is specified by the developer and should correspond to the target activity that you wish to receive from Adobe Target. Docs regarding target activities are available at https://experienceleague.adobe.com/docs/target/using/activities/activities.html?lang=en and docs regarding target parameters are available at https://experienceleague.adobe.com/docs/target/using/audiences/visitor-profiles/variables-profiles-parameters-methods.html?lang=en.
