### ISSUE TITLE
Before calling AdobeTargetCall for getting getTntID, is any other way  for getting TntId.

### ISSUE THREAD

**Issue by shravanteegala** [Adobe-Marketing-Cloud/acp-sdks#691]
Hi team,
Using ACP Target.(Objective- c 2.x)
we need to get getTntID , here when we get tntID we needs to before call AdobeTargetCall method.
so, Is Any other way to getting tnTID without calling AdobeTargetCall. ?

**Comment by rymorale** [comment]
Hi @shravanteegala, the tntid is returned in the target network response after a successful target request is made. There is no way to retrieve the tntid before making a request to target.
