### ISSUE TITLE
ld: library not found for -lACPCampaign_iOS

### ISSUE THREAD

**Issue by raymondChan23** [Adobe-Marketing-Cloud/acp-sdks#695]
after add 
    pod 'ACPCampaign', '~> 1.0' 
    pod 'ACPUserProfile', '~> 2.0'
    pod 'ACPCore', '~> 2.0' 
& pod install
cannot build my app with the error
ld: library not found for -lACPCampaign_iOS
any ideas? Many thanks

**Comment by casmj** [comment]
Hi raymondChan23,

Thanks for reaching out. To fix the "ld: library not found" error in Xcode after adding the ACPCampaign, ACPUserProfile, and ACPCore pods, you could try to run `pod install` in the ios directory of the project (this may seem pretty basic, but it has helped others with similar struggles). This might resolve the issue. It seems like someone else had a similar issue at https://github.com/adobe/react-native-acpanalytics/issues/49. You might find some answers there.

Beyond this, here are a few other things you could verify and/or try:

1. **Check Podfile:** Verify that you have entered the correct pod dependencies in the podfile. For example:

```shell
    target 'Your_Target_Name' do
        use_frameworks!
        pod 'ACPCampaign', '> 1.0'
        pod 'ACPUserProfile', '> 2.0'
        pod 'ACPCore', '~> 2.0'
    end
```

2. **Ensure you are opening the `.xcworkspace` file and not the `.xcodeproj` one:** After installing the pods and whenever you're working with CocoaPods, you should always use the `.xcworkspace` file. By using the `.xcodeproj`, Xcode may not be able to find these new pods, resulting in the error.

3. **Clean and Build:** Perform a clean (Cmd + Shift + K) and then build again (Cmd + B).

4. **Reinstall Pods:** You may need to deintegrate CocoaPods from your project, delete the Pods folder and the Podfile.lock file, then reinstall CocoaPods. [This gist might provide some help with that](https://gist.github.com/mbinna/4202236).


5. **Update Cocoapods:** Lastly, it might also help to make sure your Cocoapods installation is up to date. You can update Cocoapods by running `sudo gem install cocoapods`.

If after these steps the issue still persists, you might want to check your project's Linked Frameworks and Libraries in the General tab of your Target's settings. These libraries should have been added there by CocoaPods, if any of these are missing, you might need to add them manually. 

It is also a good idea to check the Build Phases tab in your Target settings to make sure the libraries are listed under "Link Binary With Libraries".

Casey

**Comment by cacheung** [comment]
Hi raymondChan23,

We hope the information Casey provided was helpful. Before we close the issue, is there anything else you need further assistance with? If you don't have any further inquiries, we'll proceed with closing the issue. 

Calise

**Comment by raymondChan23** [comment]
Hi Calise,

I have followed the steps and checked the Build Phases tab in your Target
settings to make sure the libraries are listed under "Link Binary With
Libraries".
But the same error occurs.

However I have tried the Manuel installation xcframework, it works. Not
sure why cocoapod install fails.

Raymond

在 2023年7月25日週二 07:45，Calise Cheung ***@***.***> 寫道：

**Comment by cacheung** [comment]
Hi Raymond,

We also have the installation instruction in the doc [here](https://developer.adobe.com/client-sdks/previous-versions/documentation/adobe-campaign-standard/#add-the-campaign-standard-extension-to-your-app).  See if it works for you.

ACP prefix extensions are the older version of SDK, there are AEP prefix sdk extensions available.  Here is the migration doc from ACP to AEP sdk for your [reference](https://developer.adobe.com/client-sdks/previous-versions/documentation/migrate-to-swift).

**Comment by cacheung** [comment]
Hi Raymond,  If you see the same issue for AEP sdk.  Please open a new issue.
