### ISSUE TITLE
watchOS Support

### ISSUE THREAD

**Issue by daveanderson** [Adobe-Marketing-Cloud/acp-sdks#96]
According to the documentation https://aep-sdks.gitbook.io/docs/resources/upgrading-to-aep/aepvs4x#os-platform-support Apple watchOS is listed as "Supported" by the Experience Platform SDKs.

When I attempt to include ACP support in my watchOS extension via

```
target "WatchAppExtension" do
    platform :watchos, '3.0'
    
    pod 'ACPCore', '~> 2.0'
end
```

I get the following error when I `pod install`

```
[!] The platform of the target `WatchAppExtension` (watchOS 3.0) is not compatible with `ACPCore (2.0.3)`, which does not support `watchos`.
```

Is the documentation incorrect or do I need to do something else to get watchOS-compatible libraries?

Note: We currently have watchOS tracking working via the v4.x SDK and do not want to lose this capability. Can we use the v4 SDK for watchOS and v5 for iOS?

**Comment by praschetan** [comment]
Hi @daveanderson - we're working on wearable support. It's set to release shortly. Please stay tuned.

**Comment by daveanderson** [comment]
Any update here?

**Comment by praschetan** [comment]
Sorry, unfortunately no. We're waiting on GM of WatchOS to drop before we decide how we proceed.

**Comment by daveanderson** [comment]
Sorry, that sounds like you won't _start_ deciding on direction until after the GM. I would have anticipated that the beta period would have been your opportunity to figure out direction, and that your support would be released concurrent with watchOS GM

**Comment by Ataman11** [comment]
Hi @praschetan, is watch os supported now?

**Comment by casmj** [comment]
Hi daveanderson and Ataman11,

We apologize for your very long wait to hear back from us on this question. At the moment there are no plans to support WatchOS. Please contact Adobe Customer Care if you need more assistance regarding WatchOS.

Sincerely,
Casey
